# Generated by Django 5.1.1 on 2026-02-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('consultation_type', models.CharField(choices=[('in_person', 'حضوری (۱ ساعت)'), ('online', 'غیرحضوری / آنلاین (۳۰ دقیقه)')], default='online', max_length=20, verbose_name='نوع مشاوره')),
                ('country', models.CharField(choices=[('china', 'چین'), ('canada', 'کانادا'), ('spain', 'اسپانیا'), ('other', 'سایر کشورها')], default='canada', max_length=20, verbose_name='کشور مقصد')),
                ('preferred_date', models.DateField(verbose_name='تاریخ پیشنهادی')),
                ('preferred_time', models.CharField(max_length=50, verbose_name='ساعت پیشنهادی')),
                ('description', models.TextField(blank=True, help_text='به صورت خلاصه شرایط و سوالات خود را بنویسید.', verbose_name='توضیحات و سوالات شما')),
                ('status', models.CharField(choices=[('new', 'ثبت شده'), ('contacted', 'تماس گرفته شده'), ('done', 'انجام شده')], default='new', max_length=20, verbose_name='وضعیت درخواست')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره',
                'verbose_name_plural': 'درخواست\u200cهای مشاوره',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال تولد')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'مجرد'), ('married', 'متاهل')], max_length=10, verbose_name='وضعیت تاهل')),
                ('apply_timeline', models.CharField(blank=True, choices=[('<1', 'کمتر از ۱ سال'), ('1-2', 'بین ۱ تا ۲ سال'), ('>2', 'بیشتر از ۲ سال')], max_length=10, verbose_name='کی قصد اپلای دارید؟')),
                ('has_financial_capacity', models.BooleanField(default=False, verbose_name='تمکن مالی بالای یک میلیارد تومان دارم')),
                ('current_degree', models.CharField(choices=[('diploma', 'دیپلم'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], max_length=20, verbose_name='آخرین مدرک تحصیلی')),
                ('field_of_study', models.CharField(max_length=150, verbose_name='رشته تحصیلی فعلی / قبلی')),
                ('average_grade', models.CharField(help_text='مثلاً ۱۸.۵', max_length=20, verbose_name='معدل (تقریبی)')),
                ('graduation_year', models.CharField(blank=True, max_length=10, verbose_name='سال فارغ التحصیلی')),
                ('target_country', models.CharField(choices=[('china', 'چین'), ('canada', 'کانادا'), ('spain', 'اسپانیا'), ('other', 'سایر کشورها')], default='canada', max_length=20, verbose_name='کشور مقصد')),
                ('language_test_type', models.CharField(choices=[('none', 'ندارم'), ('ielts', 'IELTS'), ('toefl', 'TOEFL'), ('duolingo', 'Duolingo'), ('pte', 'PTE'), ('delf', 'DELF/DALF'), ('testdaf', 'TestDaF'), ('sat', 'SAT'), ('yos', 'YOS')], default='none', max_length=20, verbose_name='نوع آزمون زبان')),
                ('has_ielts', models.BooleanField(default=False, help_text='در صورت داشتن هر نوع مدرک زبان این گزینه را فعال کنید.', verbose_name='مدرک زبان (آیلتس/تافل) دارم')),
                ('language_score', models.CharField(blank=True, max_length=50, verbose_name='نمره زبان (در صورت وجود)')),
                ('has_journal_article', models.BooleanField(default=False, verbose_name='مقاله ژورنالی')),
                ('has_conference_article', models.BooleanField(default=False, verbose_name='مقاله کنفرانسی')),
                ('has_book', models.BooleanField(default=False, verbose_name='چاپ یا ترجمه کتاب')),
                ('has_international_tests', models.BooleanField(default=False, verbose_name='آزمون\u200cهای بین\u200cالملل (SAT, GRE, GMAT ...)')),
                ('desired_countries', models.CharField(blank=True, help_text='مثلاً چین، کانادا، اسپانیا یا سایر کشورها', max_length=200, verbose_name='کشورهای مورد نظر')),
                ('desired_major', models.CharField(blank=True, max_length=150, verbose_name='رشته مورد نظر (اختیاری)')),
                ('service_scope', models.CharField(blank=True, choices=[('full', 'تمام فرآیند پذیرش و ویزا'), ('partial', 'بخشی از فرآیند پذیرش و ویزا'), ('consulting', 'تنها مشاوره دقیق و فنی می\u200cخواهم')], max_length=30, verbose_name='تمایل دارید چه بخشی از کار به موسسه سپرده شود؟')),
                ('preferred_intake', models.CharField(blank=True, max_length=50, verbose_name='ترم / سال مورد نظر برای شروع')),
                ('notes', models.TextField(blank=True, help_text='اولویت\u200cها، بودجه تقریبی، کشور یا دانشگاه\u200cهای مورد علاقه و ...', verbose_name='توضیحات تکمیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'درخواست ارزیابی',
                'verbose_name_plural': 'درخواست\u200cهای ارزیابی',
                'ordering': ['-created_at'],
            },
        ),
    ]
