# Generated by Django 5.1.1 on 2026-02-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='برای آدرس صفحه، فقط حروف انگلیسی و خط تیره.', max_length=150, unique=True, verbose_name='شناسه آدرس (انگلیسی)')),
                ('name_fa', models.CharField(max_length=200, verbose_name='نام فارسی')),
                ('name_en', models.CharField(max_length=200, verbose_name='نام انگلیسی')),
                ('country', models.CharField(choices=[('china', 'چین'), ('canada', 'کانادا'), ('spain', 'اسپانیا'), ('other', 'سایر کشورها')], max_length=20, verbose_name='کشور')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('type', models.CharField(choices=[('university', 'دانشگاه'), ('college', 'کالج'), ('school', 'مدرسه'), ('institute', 'موسسه')], default='university', max_length=20, verbose_name='نوع موسسه')),
                ('world_rank', models.CharField(blank=True, help_text='مثلاً 2 یا 101-150', max_length=50, verbose_name='رتبه جهانی')),
                ('is_approved_by_mo_science', models.BooleanField(default=True, verbose_name='مورد تایید وزارت علوم')),
                ('is_approved_by_mo_health', models.BooleanField(default=False, verbose_name='مورد تایید وزارت بهداشت')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت دانشگاه')),
                ('short_description', models.TextField(blank=True, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات کامل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دانشگاه / موسسه',
                'verbose_name_plural': 'دانشگاه\u200cها و موسسات',
                'ordering': ['country', 'city', 'name_fa'],
            },
        ),
    ]
