# Generated by Django 5.1.1 on 2026-02-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('slug', models.SlugField(help_text='برای آدرس صفحه، فقط حروف انگلیسی و خط تیره.', max_length=250, unique=True, verbose_name='شناسه آدرس')),
                ('excerpt', models.TextField(blank=True, verbose_name='خلاصه مطلب')),
                ('content', models.TextField(verbose_name='متن کامل')),
                ('image', models.URLField(blank=True, help_text='آدرس تصویر؛ در صورت خالی بودن از تصویر پیش\u200cفرض استفاده می\u200cشود.', verbose_name='آدرس تصویر شاخص')),
                ('country_tag', models.CharField(blank=True, help_text='مثلاً چین، کانادا، اسپانیا، خبری، خدمات موسسه', max_length=100, verbose_name='برچسب کشور / دسته')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'پست وبلاگ',
                'verbose_name_plural': 'پست\u200cهای وبلاگ',
                'ordering': ['-created_at'],
            },
        ),
    ]
