# Generated by Django 5.1.1 on 2026-02-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blog_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان دوره')),
                ('slug', models.SlugField(help_text='برای آدرس صفحه، فقط حروف انگلیسی و خط تیره.', max_length=250, unique=True, verbose_name='شناسه آدرس')),
                ('short_description', models.TextField(blank=True, verbose_name='خلاصه')),
                ('objectives', models.TextField(blank=True, verbose_name='اهداف دوره')),
                ('conditions', models.TextField(blank=True, verbose_name='شرایط و پیش\u200cنیازها')),
                ('image', models.URLField(blank=True, verbose_name='آدرس تصویر')),
                ('country', models.CharField(blank=True, choices=[('china', 'چین'), ('canada', 'کانادا'), ('spain', 'اسپانیا'), ('other', 'سایر کشورها')], max_length=20, verbose_name='کشور مرتبط')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان رشته')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('country', models.CharField(blank=True, choices=[('china', 'چین'), ('canada', 'کانادا'), ('spain', 'اسپانیا'), ('other', 'سایر کشورها')], max_length=20, verbose_name='کشور مرتبط')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'رشته تحصیلی',
                'verbose_name_plural': 'رشته\u200cهای تحصیلی',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('icon', models.CharField(blank=True, help_text='مثلاً ti-comments-smiley یا ti-email', max_length=80, verbose_name='کلاس آیکون')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات موسسه',
                'ordering': ['order', 'id'],
            },
        ),
    ]
