# Generated by Django 5.1.1 on 2026-02-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seed_default_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='image',
            field=models.URLField(blank=True, help_text='مثلاً /static/img/universities/toronto.jpg یا یک URL کامل', verbose_name='آدرس تصویر دانشگاه'),
        ),
    ]
