# Generated by Django 5.1.1 on 2026-02-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_university_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='image',
            field=models.FileField(blank=True, help_text='تصویر را اینجا آپلود کنید.', null=True, upload_to='universities/', verbose_name='تصویر دانشگاه'),
        ),
    ]
