# Generated by Django 5.1.1 on 2026-02-25 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_university_image_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='meta_description',
            field=models.TextField(blank=True, help_text='خلاصه صفحه برای موتورهای جستجو (۱۵۰–۱۶۰ کاراکتر توصیه می\u200cشود).', verbose_name='توضیح SEO'),
        ),
        migrations.AddField(
            model_name='university',
            name='meta_title',
            field=models.CharField(blank=True, help_text='برای موتورهای جستجو؛ در صورت خالی بودن از نام دانشگاه استفاده می\u200cشود.', max_length=200, verbose_name='عنوان SEO'),
        ),
        migrations.CreateModel(
            name='UniversityContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'متن'), ('image', 'تصویر'), ('image_text', 'تصویر + متن')], default='text', max_length=20, verbose_name='نوع بلاک')),
                ('size', models.CharField(choices=[('full', 'تمام عرض'), ('half', 'نیم عرض'), ('third', 'یک\u200cسوم عرض')], default='full', max_length=20, verbose_name='عرض نمایش')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('content', models.TextField(blank=True, verbose_name='متن (می\u200cتوانید از HTML استفاده کنید)')),
                ('image', models.FileField(blank=True, null=True, upload_to='universities/blocks/', verbose_name='تصویر')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='core.university', verbose_name='دانشگاه')),
            ],
            options={
                'verbose_name': 'بلاک محتوا',
                'verbose_name_plural': 'بلاک\u200cهای محتوا',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UniversityGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='universities/gallery/', verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='عنوان / توضیح تصویر')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.university', verbose_name='دانشگاه')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'تصاویر گالری',
                'ordering': ['order', 'id'],
            },
        ),
    ]
