# Generated by Django 5.1.1 on 2026-02-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_university_seo_gallery_blocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitycontentblock',
            name='block_type',
        ),
        migrations.RemoveField(
            model_name='universitycontentblock',
            name='image',
        ),
        migrations.AlterField(
            model_name='universitycontentblock',
            name='content',
            field=models.TextField(blank=True, verbose_name='محتوا (متن و تصویر تو در تو)'),
        ),
        migrations.AlterField(
            model_name='universitycontentblock',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان بلاک'),
        ),
    ]
