# Generated by Django 5.1.1 on 2026-02-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_simplify_content_block'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniversityContentBlock',
        ),
    ]
