# Generated by Django 5.1.1 on 2026-02-25 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_content_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='interest_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_requests', to='core.university', verbose_name='دانشگاه مورد علاقه'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='preferred_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پیشنهادی'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='ساعت پیشنهادی'),
        ),
    ]
