# Generated by Django 5.1.1 on 2026-02-25 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_seed_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('time_label', models.CharField(max_length=50, verbose_name='بازه زمانی')),
                ('is_booked', models.BooleanField(default=False, verbose_name='رزرو شده')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'زمان مشاوره',
                'verbose_name_plural': 'زمان\u200cهای مشاوره',
                'ordering': ['date', 'order', 'id'],
                'unique_together': {('date', 'time_label')},
            },
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_requests', to='core.consultationslot', verbose_name='زمان رزرو'),
        ),
    ]
