# Generated by Django 5.1.1 on 2026-02-25 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_seed_consultation_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationrequest',
            name='preferred_date',
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='preferred_time',
        ),
    ]
