# Generated by Django 5.1.1 on 2026-02-26 07:53

from django.db import migrations, models


def create_default_institute(apps, schema_editor):
    Institute = apps.get_model("core", "Institute")
    Institute.objects.get_or_create(
        id=1,
        defaults={
            "name": "سفیران آینده روشن",
            "province": "مازندران",
            "city": "بابل",
            "type_title": "فرآیند صدور مجوز موسسات اعزام دانشجو به خارج",
            "phone": "01132350320",
            "email": "saroshanbbl@gmail.com",
            "address": "کمربند امیر کلا، جنب موسسه آموزش عالی علوم و فناوری آریان، مجتمع ایرانیکا، طبقه اول",
            "website": "www.saroshan.ir",
            "license_issue_date": "1403/05/22",
            "license_expiry_date": "1403/05/22",
            "students_sent": 0,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_preferred_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام موسسه')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('type_title', models.CharField(max_length=200, verbose_name='عنوان نوع مجوز')),
                ('phone', models.CharField(max_length=20, verbose_name='تلفن')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('website', models.CharField(blank=True, max_length=200, verbose_name='وب\u200cسایت')),
                ('license_issue_date', models.CharField(max_length=20, verbose_name='تاریخ صدور مجوز')),
                ('license_expiry_date', models.CharField(blank=True, max_length=20, verbose_name='تاریخ انقضای مجوز')),
                ('students_sent', models.PositiveIntegerField(default=0, verbose_name='تعداد دانشجویان اعزام\u200cشده')),
            ],
            options={
                'verbose_name': 'اطلاعات موسسه',
                'verbose_name_plural': 'اطلاعات موسسه',
            },
        ),
        migrations.RunPython(create_default_institute, migrations.RunPython.noop),
    ]
