# Generated by Django 5.1.1 on 2026-02-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='countries_count',
            field=models.PositiveIntegerField(default=0, verbose_name='کشور مقصد'),
        ),
    ]
