# Generated by Django 5.1.1 on 2026-02-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_countries_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('position', models.CharField(max_length=150, verbose_name='سمت')),
                ('image', models.FileField(help_text='عکس عضو تیم (الزامی)', upload_to='team/', verbose_name='عکس')),
                ('title', models.CharField(blank=True, help_text='مثلاً مشاور ارشد، کارشناس پذیرش', max_length=200, verbose_name='عنوان / مدرک')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('description', models.TextField(blank=True, help_text='معرفی کوتاه یا طولانی عضو تیم', verbose_name='توضیحات')),
                ('telegram', models.URLField(blank=True, verbose_name='تلگرام')),
                ('whatsapp', models.CharField(blank=True, help_text='شماره با کد کشور، مثلاً 989123456789', max_length=20, verbose_name='واتساپ')),
                ('instagram', models.URLField(blank=True, verbose_name='اینستاگرام')),
                ('linkedin', models.URLField(blank=True, verbose_name='لینکدین')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت شخصی')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'عضو تیم',
                'verbose_name_plural': 'اعضای تیم',
                'ordering': ['order', 'id'],
            },
        ),
    ]
