# Generated by Django 5.1.1 on 2026-02-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_major_detail_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات کامل'),
        ),
        migrations.AlterModelTable(
            name='blogpost',
            table='core_blogpost',
        ),
        migrations.AlterModelTable(
            name='consultationrequest',
            table='core_consultationrequest',
        ),
        migrations.AlterModelTable(
            name='consultationslot',
            table='core_consultationslot',
        ),
        migrations.AlterModelTable(
            name='contactmessage',
            table='core_contactmessage',
        ),
        migrations.AlterModelTable(
            name='course',
            table='core_course',
        ),
        migrations.AlterModelTable(
            name='evaluationrequest',
            table='core_evaluationrequest',
        ),
        migrations.AlterModelTable(
            name='faq',
            table='core_faq',
        ),
        migrations.AlterModelTable(
            name='institute',
            table='core_institute',
        ),
        migrations.AlterModelTable(
            name='major',
            table='core_major',
        ),
        migrations.AlterModelTable(
            name='service',
            table='core_service',
        ),
        migrations.AlterModelTable(
            name='teammember',
            table='core_teammember',
        ),
        migrations.AlterModelTable(
            name='university',
            table='core_university',
        ),
        migrations.AlterModelTable(
            name='universitygalleryimage',
            table='core_universitygalleryimage',
        ),
    ]
