# Generated by Django 5.1.1 on 2026-02-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_major_description_alter_blogpost_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='favicon',
            field=models.FileField(blank=True, help_text='آیکون favicon برای تب مرورگر.', null=True, upload_to='institute/', verbose_name='آیکون تب مرورگر'),
        ),
        migrations.AddField(
            model_name='institute',
            name='logo',
            field=models.FileField(blank=True, help_text='لوگوی موسسه برای هدر و فوتر؛ در صورت خالی بودن از لوگوی پیش\u200cفرض استفاده می\u200cشود.', null=True, upload_to='institute/', verbose_name='لوگوی موسسه'),
        ),
    ]
