# Generated by Django 4.2.25 on 2026-02-26 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_institute_logo_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=350, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سوال متداول دوره',
                'verbose_name_plural': 'سوالات متداول دوره',
                'db_table': 'core_course_faq',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='institute',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='logo',
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_published', 'created_at'], name='blog_published_created_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['country_tag'], name='blog_country_tag_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['consultation_type'], name='consult_type_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['country'], name='consult_country_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['status'], name='consult_status_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['created_at'], name='consult_created_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationslot',
            index=models.Index(fields=['date', 'is_booked'], name='slot_date_booked_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['country', 'city'], name='uni_country_city_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['type'], name='uni_type_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['name_fa'], name='uni_name_fa_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['name_en'], name='uni_name_en_idx'),
        ),
        migrations.AddField(
            model_name='coursefaq',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.course', verbose_name='دوره'),
        ),
    ]
