# Generated by Django 4.2.25 on 2026-02-26 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_coursefaq_remove_institute_favicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=350, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.university', verbose_name='دانشگاه')),
            ],
            options={
                'verbose_name': 'سوال متداول دانشگاه',
                'verbose_name_plural': 'سوالات متداول دانشگاه',
                'db_table': 'core_university_faq',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MajorFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=350, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.major', verbose_name='رشته')),
            ],
            options={
                'verbose_name': 'سوال متداول رشته',
                'verbose_name_plural': 'سوالات متداول رشته',
                'db_table': 'core_major_faq',
                'ordering': ['order', 'id'],
            },
        ),
    ]
