# Generated by Django 4.2.16 on 2026-05-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_universityfaq_majorfaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='اختیاری؛ اگر وارد شود به عنوان canonical این پست استفاده می\u200cشود.', verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True, help_text='توضیح متا (حدود ۱۵۰ تا ۱۶۰ کاراکتر توصیه می\u200cشود).', verbose_name='توضیحات SEO'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='کلمات کلیدی را با ویرگول جدا کنید.', max_length=300, verbose_name='کلمات کلیدی SEO'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='در صورت خالی بودن از عنوان مطلب استفاده می\u200cشود.', max_length=200, verbose_name='عنوان SEO'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, help_text='تصویر را آپلود کنید. فایل به\u200cصورت خودکار تا حداکثر ۷۰۰KB فشرده می\u200cشود.', null=True, upload_to='blog/', verbose_name='تصویر شاخص'),
        ),
    ]
