# Generated by Django 4.2.28 on 2026-05-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_blogpost_canonical_url_blogpost_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='consultation_type',
            field=models.CharField(choices=[('in_person', 'حضوری (۳۰ دقیقه)'), ('online', 'غیرحضوری / آنلاین (۳۰ دقیقه)')], default='online', max_length=20, verbose_name='نوع مشاوره'),
        ),
    ]
