# Generated by Django 5.0.7 on 2026-05-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_faq_detail_page_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، این سوال در باکس «سوالات پرتکرار» زیر دسته\u200cبندی\u200cها در صفحه FAQ نمایش داده می\u200cشود.', verbose_name='سوالات پرتکرار'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='slug',
            field=models.SlugField(blank=True, help_text='برای لینک مستقیم به سوال؛ در صورت خالی بودن خودکار ساخته می\u200cشود.', max_length=200, unique=True, verbose_name='شناسه لینک'),
        ),
    ]
