# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_monthly_achievement"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, verbose_name="نام دسته")),
                ("slug", models.SlugField(max_length=120, unique=True, verbose_name="شناسه")),
                ("description", models.TextField(blank=True, verbose_name="توضیح کوتاه")),
                ("icon", models.CharField(blank=True, max_length=80, verbose_name="کلاس آیکون")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "دسته تعرفه",
                "verbose_name_plural": "دسته‌های تعرفه",
                "db_table": "core_pricingcategory",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LivingAllowanceCountry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="نام کشور / منطقه")),
                ("slug", models.SlugField(max_length=200, unique=True, verbose_name="شناسه")),
                ("amount", models.PositiveBigIntegerField(verbose_name="میزان مقرری")),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "یورو"),
                            ("USD", "دلار آمریکا"),
                            ("GBP", "پوند انگلیس"),
                            ("AUD", "دلار استرالیا"),
                            ("CAD", "دلار کانادا"),
                            ("CHF", "فرانک سوئیس"),
                            ("DKK", "کرون دانمارک"),
                            ("SEK", "کرون سوئد"),
                            ("NOK", "کرون نروژ"),
                            ("JPY", "ین ژاپن"),
                        ],
                        default="EUR",
                        max_length=10,
                        verbose_name="واحد پول",
                    ),
                ),
                (
                    "search_keywords",
                    models.CharField(
                        blank=True,
                        help_text="برای جستجوی سریع در ماشین‌حساب؛ با فاصله جدا شود.",
                        max_length=250,
                        verbose_name="کلمات جستجو",
                    ),
                ),
                (
                    "region_group",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً اروپا، انگلستان",
                        max_length=80,
                        verbose_name="گروه منطقه",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "مقرری کشور",
                "verbose_name_plural": "مقرری کشورها",
                "db_table": "core_livingallowancecountry",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PricingTariff",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="عنوان خدمت")),
                ("slug", models.SlugField(max_length=200, unique=True, verbose_name="شناسه")),
                ("short_description", models.TextField(blank=True, verbose_name="خلاصه")),
                (
                    "description",
                    models.TextField(
                        help_text="شرح کامل خدمت برای نمایش در صفحه تعرفه.",
                        verbose_name="توضیحات کامل",
                    ),
                ),
                (
                    "calculator_key",
                    models.CharField(
                        help_text="شناسه یکتا برای منطق پیشنهاددهنده؛ مثلاً visa_application",
                        max_length=60,
                        unique=True,
                        verbose_name="کلید ماشین‌حساب",
                    ),
                ),
                (
                    "price_toman",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="۰ = تماس بگیرید یا بسته به پرونده",
                        verbose_name="قیمت (تومان)",
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[("fixed", "مبلغ ثابت"), ("from", "از (حداقل)"), ("contact", "تماس بگیرید")],
                        default="fixed",
                        max_length=20,
                        verbose_name="نوع نمایش قیمت",
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=80, verbose_name="کلاس آیکون")),
                (
                    "is_calculator_option",
                    models.BooleanField(
                        default=True,
                        help_text="کاربر می‌تواند این خدمت را در پیشنهاد نهایی ببیند/حذف کند.",
                        verbose_name="قابل انتخاب در ماشین‌حساب",
                    ),
                ),
                (
                    "is_core",
                    models.BooleanField(
                        default=False,
                        help_text="در پکیج‌های پیشنهادی معمولاً خودکار اضافه می‌شود.",
                        verbose_name="خدمت پایه",
                    ),
                ),
                (
                    "auto_for_goals",
                    models.CharField(
                        blank=True,
                        help_text="کلیدهای هدف جدا شده با کاما: study,language,visa_only,docs_only",
                        max_length=120,
                        verbose_name="اهداف مرتبط",
                    ),
                ),
                (
                    "depends_on_keys",
                    models.CharField(
                        blank=True,
                        help_text="کلیدهای calculator که باید انتخاب شده باشند؛ با کاما جدا شود.",
                        max_length=200,
                        verbose_name="وابسته به خدمات",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tariffs",
                        to="core.pricingcategory",
                        verbose_name="دسته",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعرفه خدمت",
                "verbose_name_plural": "تعرفه خدمات",
                "db_table": "core_pricingtariff",
                "ordering": ["order", "id"],
            },
        ),
    ]
