# Generated by Django 5.0.7 on 2026-05-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_teammember_member_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyachievement',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='برای URL صفحه اختصاصی؛ خالی بماند تا خودکار ساخته شود.', max_length=200, unique=True, verbose_name='آدرس صفحه'),
        ),
        migrations.AlterField(
            model_name='service',
            name='highlights',
            field=models.TextField(blank=True, help_text='هر خط یک مورد (نمایش در کارت بازشده).', verbose_name='نکات کلیدی'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='در بخش «پرطرفدار» صفحه خدمات نمایش داده می\u200cشود.', verbose_name='خدمات پرطرفدار'),
        ),
        migrations.AlterField(
            model_name='service',
            name='search_keywords',
            field=models.TextField(blank=True, help_text='کلمات مرتبط با کاما جدا کنید تا در جستجو بهتر دیده شود.', verbose_name='کلمات کلیدی جستجو'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True, help_text='خلاصه برای نمایش در کارت\u200cها و صفحه اصلی.', verbose_name='توضیح کوتاه (کارت و صفحه اول)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='برای لینک مستقیم به خدمت؛ در صورت خالی بودن خودکار ساخته می\u200cشود.', max_length=200, unique=True, verbose_name='شناسه لینک'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(blank=True, help_text='کلاس آیکون Themify، مثلاً ti-headphone-alt', max_length=60, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='meta_title',
            field=models.CharField(blank=True, help_text='اگر خالی باشد از نام دسته استفاده می\u200cشود.', max_length=70, verbose_name='عنوان سئو'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(help_text='برای آدرس صفحه دسته، مثلاً moshavere یا visa', max_length=150, unique=True, verbose_name='شناسه آدرس'),
        ),
    ]
