# Generated by Django 5.0.7 on 2026-05-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_university_major_link'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='consultationslot',
            name='slot_is_booked_idx',
        ),
        migrations.RenameIndex(
            model_name='major',
            new_name='core_major_is_acti_bf4e84_idx',
            old_name='core_major_active_country_idx',
        ),
        migrations.RenameIndex(
            model_name='major',
            new_name='core_major_is_acti_95801f_idx',
            old_name='core_major_active_order_idx',
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='photo',
            field=models.ImageField(blank=True, help_text='اختیاری؛ پس از آپلود تا حداکثر ۳۰۰KB فشرده می\u200cشود. در صورت خالی بودن آواتار پیش\u200cفرض نمایش داده می\u200cشود.', null=True, upload_to='blog/authors/', verbose_name='عکس'),
        ),
    ]
