# Generated by Django 5.2.14 on 2026-05-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_major_meta_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='referral_detail',
            field=models.CharField(blank=True, help_text='مثلاً عبارت جستجو در گوگل یا توضیح «سایر»', max_length=200, verbose_name='جزئیات منبع'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='referral_social_platform',
            field=models.CharField(blank=True, max_length=16, verbose_name='شبکه اجتماعی'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='referral_source',
            field=models.CharField(blank=True, db_index=True, max_length=24, verbose_name='از کجا با ما آشنا شدید؟'),
        ),
        migrations.AddField(
            model_name='evaluationrequest',
            name='referral_detail',
            field=models.CharField(blank=True, help_text='مثلاً عبارت جستجو در گوگل یا توضیح «سایر»', max_length=200, verbose_name='جزئیات منبع'),
        ),
        migrations.AddField(
            model_name='evaluationrequest',
            name='referral_social_platform',
            field=models.CharField(blank=True, max_length=16, verbose_name='شبکه اجتماعی'),
        ),
        migrations.AddField(
            model_name='evaluationrequest',
            name='referral_source',
            field=models.CharField(blank=True, db_index=True, max_length=24, verbose_name='از کجا با ما آشنا شدید؟'),
        ),
    ]
