# Generated by Django 5.2.14 on 2026-05-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_browse_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='country',
            field=models.CharField(choices=[('canada', 'کانادا'), ('spain', 'اسپانیا'), ('china', 'چین'), ('other', 'سایر کشورها')], default='canada', max_length=20, verbose_name='کشور مقصد'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='referral_social_platform',
            field=models.CharField(blank=True, choices=[('bale', 'بله'), ('eitaa', 'ایتا'), ('telegram', 'تلگرام'), ('instagram', 'اینستاگرام')], max_length=16, verbose_name='شبکه اجتماعی'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('website', 'سایت saroshan.ir'), ('google', 'گوگل / جستجو'), ('social', 'شبکه اجتماعی'), ('friend', 'معرفی دوستان یا آشنایان'), ('university', 'دانشگاه / مدرسه / استاد'), ('advertisement', 'تبلیغات (بیلبورد، پیامک و …)'), ('other', 'سایر')], db_index=True, max_length=24, verbose_name='از کجا با ما آشنا شدید؟'),
        ),
        migrations.AlterField(
            model_name='course',
            name='country',
            field=models.CharField(blank=True, choices=[('canada', 'کانادا'), ('spain', 'اسپانیا'), ('china', 'چین'), ('other', 'سایر کشورها')], max_length=20, verbose_name='کشور مرتبط'),
        ),
        migrations.AlterField(
            model_name='evaluationrequest',
            name='referral_social_platform',
            field=models.CharField(blank=True, choices=[('bale', 'بله'), ('eitaa', 'ایتا'), ('telegram', 'تلگرام'), ('instagram', 'اینستاگرام')], max_length=16, verbose_name='شبکه اجتماعی'),
        ),
        migrations.AlterField(
            model_name='evaluationrequest',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('website', 'سایت saroshan.ir'), ('google', 'گوگل / جستجو'), ('social', 'شبکه اجتماعی'), ('friend', 'معرفی دوستان یا آشنایان'), ('university', 'دانشگاه / مدرسه / استاد'), ('advertisement', 'تبلیغات (بیلبورد، پیامک و …)'), ('other', 'سایر')], db_index=True, max_length=24, verbose_name='از کجا با ما آشنا شدید؟'),
        ),
        migrations.AlterField(
            model_name='evaluationrequest',
            name='target_country',
            field=models.CharField(choices=[('canada', 'کانادا'), ('spain', 'اسپانیا'), ('china', 'چین'), ('other', 'سایر کشورها')], default='canada', max_length=20, verbose_name='کشور مقصد'),
        ),
        migrations.AlterField(
            model_name='major',
            name='country',
            field=models.CharField(blank=True, choices=[('canada', 'کانادا'), ('spain', 'اسپانیا'), ('china', 'چین'), ('uk', 'انگلستان'), ('usa', 'آمریکا'), ('australia', 'استرالیا'), ('germany', 'آلمان'), ('italy', 'ایتالیا'), ('france', 'فرانسه'), ('netherlands', 'هلند'), ('switzerland', 'سوئیس'), ('japan', 'ژاپن'), ('south_korea', 'کره جنوبی'), ('singapore', 'سنگاپور'), ('hong_kong', 'هنگ\u200cکنگ'), ('ireland', 'ایرلند'), ('sweden', 'سوئد'), ('belgium', 'بلژیک'), ('austria', 'اتریش'), ('new_zealand', 'نیوزیلند'), ('denmark', 'دانمارک'), ('finland', 'فنلاند'), ('norway', 'نروژ'), ('portugal', 'پرتغال'), ('poland', 'لهستان'), ('czech', 'جمهوری چک'), ('hungary', 'مجارستان'), ('greece', 'یونان'), ('turkey', 'ترکیه'), ('malaysia', 'مالزی'), ('uae', 'امارات'), ('saudi_arabia', 'عربستان'), ('qatar', 'قطر'), ('india', 'هند'), ('thailand', 'تایلند'), ('israel', 'اسرائیل'), ('brazil', 'برزیل'), ('mexico', 'مکزیک'), ('argentina', 'آرژانتین'), ('chile', 'شیلی'), ('south_africa', 'آفریقای جنوبی'), ('egypt', 'مصر'), ('russia', 'روسیه'), ('taiwan', 'تایوان'), ('other', 'سایر کشورها')], max_length=20, verbose_name='کشور مرتبط'),
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.CharField(choices=[('canada', 'کانادا'), ('spain', 'اسپانیا'), ('china', 'چین'), ('uk', 'انگلستان'), ('usa', 'آمریکا'), ('australia', 'استرالیا'), ('germany', 'آلمان'), ('italy', 'ایتالیا'), ('france', 'فرانسه'), ('netherlands', 'هلند'), ('switzerland', 'سوئیس'), ('japan', 'ژاپن'), ('south_korea', 'کره جنوبی'), ('singapore', 'سنگاپور'), ('hong_kong', 'هنگ\u200cکنگ'), ('ireland', 'ایرلند'), ('sweden', 'سوئد'), ('belgium', 'بلژیک'), ('austria', 'اتریش'), ('new_zealand', 'نیوزیلند'), ('denmark', 'دانمارک'), ('finland', 'فنلاند'), ('norway', 'نروژ'), ('portugal', 'پرتغال'), ('poland', 'لهستان'), ('czech', 'جمهوری چک'), ('hungary', 'مجارستان'), ('greece', 'یونان'), ('turkey', 'ترکیه'), ('malaysia', 'مالزی'), ('uae', 'امارات'), ('saudi_arabia', 'عربستان'), ('qatar', 'قطر'), ('india', 'هند'), ('thailand', 'تایلند'), ('israel', 'اسرائیل'), ('brazil', 'برزیل'), ('mexico', 'مکزیک'), ('argentina', 'آرژانتین'), ('chile', 'شیلی'), ('south_africa', 'آفریقای جنوبی'), ('egypt', 'مصر'), ('russia', 'روسیه'), ('taiwan', 'تایوان'), ('other', 'سایر کشورها')], max_length=20, verbose_name='کشور'),
        ),
    ]
