# Generated by Django 5.2.15 on 2026-06-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_evaluation_section_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationrequest',
            name='target_country',
            field=models.CharField(choices=[('canada', 'کانادا'), ('spain', 'اسپانیا'), ('china', 'چین'), ('germany', 'آلمان'), ('italy', 'ایتالیا'), ('uk', 'انگلستان'), ('usa', 'آمریکا'), ('australia', 'استرالیا'), ('other', 'سایر کشورها')], default='canada', max_length=20, verbose_name='کشور مقصد'),
        ),
    ]
