# Generated by Django 4.2.28 on 2026-07-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_evaluationrequest_target_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='تلفن ثابت'),
        ),
    ]
