"""
داده تعرفه صفحه /تعرفه-خدمات/ — دسته‌ها و خدمات با قیمت ارزی (یورو / دلار کانادا و …).
"""

from __future__ import annotations

# دسته‌های نمایشی (slug ثابت برای سئو و ناوبری)
PRICING_CATEGORIES = [
    {
        "slug": "consult",
        "name": "مشاوره و ارزیابی",
        "description": "مشاوره تخصصی و بررسی اولیه پرونده",
        "icon": "ti-comments-smiley",
        "order": 1,
    },
    {
        "slug": "documents",
        "name": "مدارک و ترجمه",
        "description": "آماده‌سازی، ترجمه و تنظیم مدارک",
        "icon": "ti-files",
        "order": 2,
    },
    {
        "slug": "apply",
        "name": "اپلای و پذیرش",
        "description": "انتخاب دانشگاه و ارسال درخواست پذیرش",
        "icon": "ti-book",
        "order": 3,
    },
    {
        "slug": "visa",
        "name": "ویزا و سفارت",
        "description": "اقدام ویزا، وقت سفارت و آمادگی مصاحبه",
        "icon": "ti-id-badge",
        "order": 4,
    },
    {
        "slug": "financial",
        "name": "مقرری و تمکن",
        "description": "گواهی مقرری و مشاوره تمکن مالی",
        "icon": "ti-money",
        "order": 5,
    },
]

# calculator_key یکتا — (slug, title, category_slug, short, description, foreign_amount, currency, allowance_percent, price_type, icon, calc_option, is_core, goals, depends, order)
PRICING_TARIFFS = [
    (
        "consultation-session",
        "مشاوره تخصصی (هر جلسه)",
        "consultation",
        "consult",
        "ارائه مشاوره درباره کشور، دانشگاه، رشته، هزینه‌ها و روادید — مطابق ماده ۳-۱ قرارداد.",
        "هر جلسه با کارشناس؛ مبلغ بر اساس کشور مقصد در جدول زیر (یورو، دلار کانادا و …).",
        0,
        "",
        None,
        "fixed",
        "ti-headphone-alt",
        True,
        False,
        "study,language,visa_only,docs_only",
        "",
        1,
    ),
    (
        "profile-evaluation",
        "ارزیابی جامع پرونده",
        "profile_evaluation",
        "consult",
        "تحلیل مدارک، سن، زبان و شانس پذیرش با گزارش کتبی.",
        "بررسی تطبیقی با معیارهای دانشگاه و سفارت؛ خروجی: کشورها و برنامه‌های پیشنهادی.",
        420,
        "EUR",
        None,
        "fixed",
        "ti-clipboard",
        True,
        True,
        "study,language",
        "",
        2,
    ),
    (
        "document-preparation",
        "آماده‌سازی و تنظیم مدارک",
        "document_preparation",
        "documents",
        "تنظیم رزومه، انگیزه‌نامه، توصیه‌نامه و چک‌لیست مدارک.",
        "بازبینی و ویرایش مطابق استاندارد دانشگاه و سفارت مقصد.",
        495,
        "EUR",
        None,
        "from",
        "ti-pencil-alt",
        True,
        True,
        "study,language,docs_only",
        "",
        3,
    ),
    (
        "official-translation",
        "ترجمه رسمی مدارک",
        "official_translation",
        "documents",
        "ترجمه رسمی مدارک تحصیلی و هویتی.",
        "هماهنگی با مترجم رسمی؛ هزینه نهایی بر اساس تعداد صفحات.",
        48,
        "EUR",
        None,
        "from",
        "ti-world",
        True,
        False,
        "study,language,visa_only,docs_only",
        "",
        4,
    ),
    (
        "courier-followup",
        "ارسال مدارک و پیگیری پرونده",
        "courier_followup",
        "documents",
        "ارسال فیزیکی مدارک و پیگیری تا نتیجه نهایی.",
        "هماهنگی پستی یا پیک به دانشگاه و سفارت.",
        115,
        "EUR",
        None,
        "fixed",
        "ti-truck",
        True,
        False,
        "study,visa_only",
        "",
        5,
    ),
    (
        "admission-service",
        "اخذ پذیرش دانشگاه",
        "admission",
        "apply",
        "اخذ پذیرش از دانشگاه‌های مورد تأیید برای کشور و مقطع درخواستی.",
        "حداکثر ۴۰٪ از یک‌ماه مقرری دانشجوی مجرد در کشور مقصد — به ارز همان کشور (ماده ۳-۲ قرارداد).",
        0,
        "",
        40,
        "from",
        "ti-medall",
        True,
        True,
        "study,language",
        "",
        6,
    ),
    (
        "contract-full-package",
        "پکیج کامل همراهی پرونده",
        "contract_full",
        "apply",
        "همراهی از مشاوره تا ویزا و استقرار.",
        "شامل مشاوره، پذیرش، ویزا، ثبت‌نام و راهنمای استقرار؛ مبالغ هر بند بر اساس مقرری کشور مقصد.",
        0,
        "",
        None,
        "from",
        "ti-package",
        True,
        False,
        "study",
        "",
        7,
    ),
    (
        "visa-service",
        "اخذ روادید تحصیلی",
        "visa",
        "visa",
        "تکمیل پرونده، هماهنگی سفارت و پیگیری تا صدور ویزا.",
        "حداکثر ۲۰٪ از یک‌ماه مقرری بورسیه مجرد — به ارز کشور مقصد (ماده ۳-۳ قرارداد).",
        0,
        "",
        20,
        "from",
        "ti-id-badge",
        True,
        True,
        "study,language,visa_only",
        "",
        8,
    ),
    (
        "embassy-appointment",
        "وقت‌گیری و هماهنگی سفارت",
        "embassy_appointment",
        "visa",
        "رزرو نوبت سفارت و چک نهایی مدارک.",
        "یادآوری زمان مراجعه و چک‌لیست روز مصاحبه.",
        135,
        "EUR",
        None,
        "fixed",
        "ti-calendar",
        True,
        False,
        "study,visa_only",
        "visa",
        9,
    ),
    (
        "interview-prep",
        "آمادگی مصاحبه ویزا",
        "interview_prep",
        "visa",
        "جلسه شبیه‌سازی مصاحبه و پاسخ به سوالات متداول.",
        "مناسب ویزای کانادا، انگلستان، آلمان و سایر کشورها.",
        195,
        "EUR",
        None,
        "fixed",
        "ti-microphone",
        True,
        False,
        "study,visa_only",
        "visa",
        10,
    ),
    (
        "registration-service",
        "ثبت‌نام در دانشگاه",
        "registration",
        "apply",
        "ثبت‌نام نهایی و ارائه اطلاعات مورد نیاز دانشگاه.",
        "حداکثر ۲۰٪ از یک‌ماه مقرری — به ارز کشور مقصد (ماده ۳-۴ قرارداد).",
        0,
        "",
        20,
        "from",
        "ti-pencil-alt",
        True,
        True,
        "study,language",
        "admission",
        11,
    ),
    (
        "relocation-service",
        "انتقال، اسکان و جانمایی",
        "relocation",
        "visa",
        "جابجایی، اقامت و راهنمایی در کشور مقصد.",
        "۲۰٪ از یک‌ماه مقرری — به ارز کشور مقصد (ماده ۳-۵ قرارداد).",
        0,
        "",
        20,
        "from",
        "ti-home",
        True,
        True,
        "study",
        "visa",
        12,
    ),
    (
        "scholarship-success-fee",
        "حق‌الزحمه اخذ بورس تحصیلی",
        "scholarship_fee",
        "financial",
        "در صورت موفقیت در اخذ بورس کامل یا نیمه‌بورس.",
        "طبق بند ۳-۷ قرارداد: درصد از مقرری و شهریه با اسناد مثبته.",
        0,
        "",
        None,
        "contact",
        "ti-star",
        False,
        False,
        "",
        "",
        13,
    ),
    (
        "living-allowance-advisory",
        "مشاوره مقرری و تمکن مالی",
        "living_allowance",
        "financial",
        "راهنمایی گواهی مقرری و مدارک تمکن.",
        "مبلغ سپرده بانکی جدا از حق‌الزحمه موسسه است؛ بر اساس جدول مقرری کشورها.",
        0,
        "",
        None,
        "contact",
        "ti-wallet",
        True,
        False,
        "study,visa_only,docs_only",
        "",
        14,
    ),
]

# مبلغ هر جلسه مشاوره به تفکیک کشور فعال موسسه
STUDY_COUNTRY_CONSULTATION = {
    "canada": (125, "CAD"),
    "spain": (75, "EUR"),
    "china": (80, "EUR"),
}

# دسته‌های قدیمی contract-* که دیگر در منو نمایش داده نمی‌شوند
DEPRECATED_CATEGORY_SLUGS = [
    "contract-consult",
    "contract-admission",
    "contract-visa",
    "contract-registration",
    "contract-relocation",
]
