"""
Top 30 universities per study country, ordered by rank (1 = highest within country).
Fields: slug, name_fa, name_en, city, world_rank, qs_rank_note, website, mo_science, mo_health
"""

CANADA_UNIVERSITIES = [
    {
        "slug": "university-of-toronto",
        "name_fa": "دانشگاه تورنتو",
        "name_en": "University of Toronto",
        "city": "تورنتو",
        "world_rank": "1",
        "qs_rank_note": "۲۱",
        "website": "https://www.utoronto.ca/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "mcgill-university",
        "name_fa": "دانشگاه مک‌گیل",
        "name_en": "McGill University",
        "city": "مونترال",
        "world_rank": "2",
        "qs_rank_note": "۳۰",
        "website": "https://www.mcgill.ca/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "university-of-british-columbia",
        "name_fa": "دانشگاه بریتیش کلمبیا",
        "name_en": "University of British Columbia",
        "city": "ونکوور",
        "world_rank": "3",
        "qs_rank_note": "۳۴",
        "website": "https://www.ubc.ca/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "university-of-alberta",
        "name_fa": "دانشگاه آلبرتا",
        "name_en": "University of Alberta",
        "city": "ادمونتون",
        "world_rank": "4",
        "qs_rank_note": "۱۱۱",
        "website": "https://www.ualberta.ca/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "universite-de-montreal",
        "name_fa": "دانشگاه مونترال",
        "name_en": "Université de Montréal",
        "city": "مونترال",
        "world_rank": "5",
        "qs_rank_note": "۱۴۱",
        "website": "https://www.umontreal.ca/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "university-of-waterloo",
        "name_fa": "دانشگاه واترلو",
        "name_en": "University of Waterloo",
        "city": "واترلو",
        "world_rank": "6",
        "qs_rank_note": "۱۱۲",
        "website": "https://uwaterloo.ca/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "western-university",
        "name_fa": "دانشگاه وسترن",
        "name_en": "Western University",
        "city": "لندن",
        "world_rank": "7",
        "qs_rank_note": "۱۱۴",
        "website": "https://www.uwo.ca/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "university-of-ottawa",
        "name_fa": "دانشگاه اتاوا",
        "name_en": "University of Ottawa",
        "city": "اتاوا",
        "world_rank": "8",
        "qs_rank_note": "۲۰۳",
        "website": "https://www.uottawa.ca/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "university-of-calgary",
        "name_fa": "دانشگاه کلگری",
        "name_en": "University of Calgary",
        "city": "کلگری",
        "world_rank": "9",
        "qs_rank_note": "۱۸۲",
        "website": "https://www.ucalgary.ca/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "queens-university",
        "name_fa": "دانشگاه کویینز",
        "name_en": "Queen's University",
        "city": "کینگستون",
        "world_rank": "10",
        "qs_rank_note": "۲۰۹",
        "website": "https://www.queensu.ca/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "dalhousie-university",
        "name_fa": "دانشگاه دالهاوزی",
        "name_en": "Dalhousie University",
        "city": "هالیفکس",
        "world_rank": "11",
        "qs_rank_note": "۲۹۸",
        "website": "https://www.dal.ca/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "simon-fraser-university",
        "name_fa": "دانشگاه سیمون فریزر",
        "name_en": "Simon Fraser University",
        "city": "برنابی",
        "world_rank": "12",
        "qs_rank_note": "۳۱۸",
        "website": "https://www.sfu.ca/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "university-of-victoria",
        "name_fa": "دانشگاه ویکتوریا",
        "name_en": "University of Victoria",
        "city": "ویکتوریا",
        "world_rank": "13",
        "qs_rank_note": "۳۲۲",
        "website": "https://www.uvic.ca/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "york-university",
        "name_fa": "دانشگاه یورک",
        "name_en": "York University",
        "city": "تورنتو",
        "world_rank": "14",
        "qs_rank_note": "۳۵۳",
        "website": "https://www.yorku.ca/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "universite-laval",
        "name_fa": "دانشگاه لاوال",
        "name_en": "Université Laval",
        "city": "کبک",
        "world_rank": "15",
        "qs_rank_note": "۴۱۶",
        "website": "https://www.ulaval.ca/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "concordia-university",
        "name_fa": "دانشگاه کنکوردیا",
        "name_en": "Concordia University",
        "city": "مونترال",
        "world_rank": "16",
        "qs_rank_note": "۳۸۷",
        "website": "https://www.concordia.ca/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "carleton-university",
        "name_fa": "دانشگاه کارلتون",
        "name_en": "Carleton University",
        "city": "اتاوا",
        "world_rank": "17",
        "qs_rank_note": "۶۰۱–۶۵۰",
        "website": "https://carleton.ca/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "university-of-saskatchewan",
        "name_fa": "دانشگاه ساسکاچوان",
        "name_en": "University of Saskatchewan",
        "city": "ساسکاتون",
        "world_rank": "18",
        "qs_rank_note": "۴۷۳",
        "website": "https://www.usask.ca/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "university-of-manitoba",
        "name_fa": "دانشگاه مانیتوبا",
        "name_en": "University of Manitoba",
        "city": "وینیپگ",
        "world_rank": "19",
        "qs_rank_note": "۶۷۱–۶۸۰",
        "website": "https://umanitoba.ca/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "memorial-university",
        "name_fa": "دانشگاه مموریال",
        "name_en": "Memorial University of Newfoundland",
        "city": "سنت جانز",
        "world_rank": "20",
        "qs_rank_note": "۷۰۱–۷۵۰",
        "website": "https://www.mun.ca/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "university-of-guelph",
        "name_fa": "دانشگاه گوئلف",
        "name_en": "University of Guelph",
        "city": "گوئلف",
        "world_rank": "21",
        "qs_rank_note": "۴۵۶",
        "website": "https://www.uoguelph.ca/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "university-of-windsor",
        "name_fa": "دانشگاه ویندزور",
        "name_en": "University of Windsor",
        "city": "ویندزور",
        "world_rank": "22",
        "qs_rank_note": "۵۴۷",
        "website": "https://www.uwindsor.ca/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "brock-university",
        "name_fa": "دانشگاه بروک",
        "name_en": "Brock University",
        "city": "سنت کاترین",
        "world_rank": "23",
        "qs_rank_note": "۶۰۱–۶۵۰",
        "website": "https://brocku.ca/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "wilfrid-laurier-university",
        "name_fa": "دانشگاه ویلفرید لوریه",
        "name_en": "Wilfrid Laurier University",
        "city": "واترلو",
        "world_rank": "24",
        "qs_rank_note": "۶۵۱–۷۰۰",
        "website": "https://www.wlu.ca/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "toronto-metropolitan-university",
        "name_fa": "دانشگاه متروپولیتن تورنتو",
        "name_en": "Toronto Metropolitan University",
        "city": "تورنتو",
        "world_rank": "25",
        "qs_rank_note": "۸۰۱–۸۵۰",
        "website": "https://www.torontomu.ca/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "university-of-regina",
        "name_fa": "دانشگاه رجاینا",
        "name_en": "University of Regina",
        "city": "رجاینا",
        "world_rank": "26",
        "qs_rank_note": "۷۰۱–۷۵۰",
        "website": "https://www.uregina.ca/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "lakehead-university",
        "name_fa": "دانشگاه لیک‌هد",
        "name_en": "Lakehead University",
        "city": "تاندر بی",
        "world_rank": "27",
        "qs_rank_note": "۷۵۱–۸۰۰",
        "website": "https://www.lakeheadu.ca/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "trent-university",
        "name_fa": "دانشگاه ترنت",
        "name_en": "Trent University",
        "city": "پیتربورو",
        "world_rank": "28",
        "qs_rank_note": "۷۵۱–۸۰۰",
        "website": "https://www.trentu.ca/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "university-of-new-brunswick",
        "name_fa": "دانشگاه نیوبرانزویک",
        "name_en": "University of New Brunswick",
        "city": "فردریکتون",
        "world_rank": "29",
        "qs_rank_note": "۷۵۱–۸۰۰",
        "website": "https://www.unb.ca/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "acadia-university",
        "name_fa": "دانشگاه آکادیا",
        "name_en": "Acadia University",
        "city": "ولفویل",
        "world_rank": "30",
        "qs_rank_note": "۸۰۱–۸۵۰",
        "website": "https://www.acadiau.ca/",
        "mo_science": True,
        "mo_health": False,
    },
]

SPAIN_UNIVERSITIES = [
    {
        "slug": "universidad-complutense-madrid",
        "name_fa": "دانشگاه کمپلوتنسه مادرید",
        "name_en": "Complutense University of Madrid",
        "city": "مادرید",
        "world_rank": "1",
        "qs_rank_note": "۱۷۱",
        "website": "https://www.ucm.es/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "universitat-de-barcelona",
        "name_fa": "دانشگاه بارسلونا",
        "name_en": "University of Barcelona",
        "city": "بارسلونا",
        "world_rank": "2",
        "qs_rank_note": "۱۶۴",
        "website": "https://www.ub.edu/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "universitat-autonoma-de-barcelona",
        "name_fa": "دانشگاه مستقل بارسلونا",
        "name_en": "Autonomous University of Barcelona",
        "city": "بارسلونا",
        "world_rank": "3",
        "qs_rank_note": "۱۴۹",
        "website": "https://www.uab.cat/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "universidad-autonoma-de-madrid",
        "name_fa": "دانشگاه مستقل مادرید",
        "name_en": "Autonomous University of Madrid",
        "city": "مادرید",
        "world_rank": "4",
        "qs_rank_note": "۱۹۹",
        "website": "https://www.uam.es/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "universidad-de-granada",
        "name_fa": "دانشگاه گرانادا",
        "name_en": "University of Granada",
        "city": "گرانادا",
        "world_rank": "5",
        "qs_rank_note": "۴۰۳",
        "website": "https://www.ugr.es/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "universitat-de-valencia",
        "name_fa": "دانشگاه والنسیا",
        "name_en": "University of Valencia",
        "city": "والنسیا",
        "world_rank": "6",
        "qs_rank_note": "۴۴۶",
        "website": "https://www.uv.es/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "universidad-de-sevilla",
        "name_fa": "دانشگاه سویا",
        "name_en": "University of Seville",
        "city": "سویا",
        "world_rank": "7",
        "qs_rank_note": "۴۸۷",
        "website": "https://www.us.es/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "universitat-pompeu-fabra",
        "name_fa": "دانشگاه پمپئو فابرا",
        "name_en": "Pompeu Fabra University",
        "city": "بارسلونا",
        "world_rank": "8",
        "qs_rank_note": "۳۱۰",
        "website": "https://www.upf.edu/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "universidad-carlos-iii-madrid",
        "name_fa": "دانشگاه کارلوس سوم مادرید",
        "name_en": "Carlos III University of Madrid",
        "city": "مادرید",
        "world_rank": "9",
        "qs_rank_note": "۳۱۹",
        "website": "https://www.uc3m.es/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "upc-barcelona-tech",
        "name_fa": "دانشگاه پلی‌تکنیک کاتالونیا",
        "name_en": "Polytechnic University of Catalonia",
        "city": "بارسلونا",
        "world_rank": "10",
        "qs_rank_note": "۳۵۴",
        "website": "https://www.upc.edu/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "universidad-de-salamanca",
        "name_fa": "دانشگاه سالامانکا",
        "name_en": "University of Salamanca",
        "city": "سالامانکا",
        "world_rank": "11",
        "qs_rank_note": "۵۳۴",
        "website": "https://www.usal.es/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "universidade-de-santiago-de-compostela",
        "name_fa": "دانشگاه سانتیاگو د کمپوستلا",
        "name_en": "University of Santiago de Compostela",
        "city": "سانتیاگو",
        "world_rank": "12",
        "qs_rank_note": "۶۰۱–۶۵۰",
        "website": "https://www.usc.es/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "universidad-del-pais-vasco",
        "name_fa": "دانشگاه کشور باسک",
        "name_en": "University of the Basque Country",
        "city": "بیلبائو",
        "world_rank": "13",
        "qs_rank_note": "۶۰۱–۶۵۰",
        "website": "https://www.ehu.eus/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "universidad-de-zaragoza",
        "name_fa": "دانشگاه ساراگوسا",
        "name_en": "University of Zaragoza",
        "city": "ساراگوسا",
        "world_rank": "14",
        "qs_rank_note": "۶۵۱–۷۰۰",
        "website": "https://www.unizar.es/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "universidad-de-murcia",
        "name_fa": "دانشگاه مورسیا",
        "name_en": "University of Murcia",
        "city": "مورسیا",
        "world_rank": "15",
        "qs_rank_note": "۷۰۱–۷۵۰",
        "website": "https://www.um.es/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "universidad-de-malaga",
        "name_fa": "دانشگاه مالاگا",
        "name_en": "University of Málaga",
        "city": "مالاگا",
        "world_rank": "16",
        "qs_rank_note": "۷۰۱–۷۵۰",
        "website": "https://www.uma.es/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "universidad-de-alicante",
        "name_fa": "دانشگاه آلیکانته",
        "name_en": "University of Alicante",
        "city": "آلیکانته",
        "world_rank": "17",
        "qs_rank_note": "۷۵۱–۸۰۰",
        "website": "https://www.ua.es/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "universidad-de-oviedo",
        "name_fa": "دانشگاه اویدو",
        "name_en": "University of Oviedo",
        "city": "اویدو",
        "world_rank": "18",
        "qs_rank_note": "۷۵۱–۸۰۰",
        "website": "https://www.uniovi.es/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "universidad-de-navarra",
        "name_fa": "دانشگاه ناوارا",
        "name_en": "University of Navarra",
        "city": "پامپلونا",
        "world_rank": "19",
        "qs_rank_note": "۲۵۳",
        "website": "https://www.unav.edu/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "ie-university",
        "name_fa": "دانشگاه IE",
        "name_en": "IE University",
        "city": "مادرید",
        "world_rank": "20",
        "qs_rank_note": "۴۰۱–۴۵۰",
        "website": "https://www.ie.edu/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "universidad-politecnica-de-madrid",
        "name_fa": "دانشگاه پلی‌تکنیک مادرید",
        "name_en": "Technical University of Madrid",
        "city": "مادرید",
        "world_rank": "21",
        "qs_rank_note": "۳۲۱",
        "website": "https://www.upm.es/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "universidad-de-valladolid",
        "name_fa": "دانشگاه وایادولید",
        "name_en": "University of Valladolid",
        "city": "وایادولید",
        "world_rank": "22",
        "qs_rank_note": "۷۰۱–۷۵۰",
        "website": "https://www.uva.es/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "universidad-rey-juan-carlos",
        "name_fa": "دانشگاه ری خوان کارلوس",
        "name_en": "King Juan Carlos University",
        "city": "مادرید",
        "world_rank": "23",
        "qs_rank_note": "۷۵۱–۸۰۰",
        "website": "https://www.urjc.es/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "universidad-de-cantabria",
        "name_fa": "دانشگاه کانتابریا",
        "name_en": "University of Cantabria",
        "city": "سانتاندر",
        "world_rank": "24",
        "qs_rank_note": "۷۵۱–۸۰۰",
        "website": "https://web.unican.es/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "universidad-de-cordoba-spain",
        "name_fa": "دانشگاه کوردوبا",
        "name_en": "University of Córdoba",
        "city": "کوردوبا",
        "world_rank": "25",
        "qs_rank_note": "۸۰۱–۸۵۰",
        "website": "https://www.uco.es/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "universidad-de-castilla-la-mancha",
        "name_fa": "دانشگاه کاستیا-لا مانچا",
        "name_en": "University of Castilla-La Mancha",
        "city": "تویدو",
        "world_rank": "26",
        "qs_rank_note": "۸۰۱–۸۵۰",
        "website": "https://www.uclm.es/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "universidad-de-la-laguna",
        "name_fa": "دانشگاه لا لاگونا",
        "name_en": "University of La Laguna",
        "city": "سان کریستوبال",
        "world_rank": "27",
        "qs_rank_note": "۸۰۱–۸۵۰",
        "website": "https://www.ull.es/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "universitat-de-les-illes-balears",
        "name_fa": "دانشگاه جزایر بالئارس",
        "name_en": "University of the Balearic Islands",
        "city": "پالما",
        "world_rank": "28",
        "qs_rank_note": "۸۰۱–۸۵۰",
        "website": "https://www.uib.es/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "universidad-de-burgos",
        "name_fa": "دانشگاه بورگوس",
        "name_en": "University of Burgos",
        "city": "بورگوس",
        "world_rank": "29",
        "qs_rank_note": "۸۵۱–۹۰۰",
        "website": "https://www.ubu.es/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "universidad-de-huelva",
        "name_fa": "دانشگاه هوئلوا",
        "name_en": "University of Huelva",
        "city": "هوئلوا",
        "world_rank": "30",
        "qs_rank_note": "۸۵۱–۹۰۰",
        "website": "https://www.uhu.es/",
        "mo_science": True,
        "mo_health": False,
    },
]

CHINA_UNIVERSITIES = [
    {
        "slug": "tsinghua-university",
        "name_fa": "دانشگاه چینهوا",
        "name_en": "Tsinghua University",
        "city": "پکن",
        "world_rank": "1",
        "qs_rank_note": "۲۰",
        "website": "https://www.tsinghua.edu.cn/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "peking-university",
        "name_fa": "دانشگاه پکن",
        "name_en": "Peking University",
        "city": "پکن",
        "world_rank": "2",
        "qs_rank_note": "۱۴",
        "website": "https://www.pku.edu.cn/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "fudan-university",
        "name_fa": "دانشگاه فودان",
        "name_en": "Fudan University",
        "city": "شانگهای",
        "world_rank": "3",
        "qs_rank_note": "۳۹",
        "website": "https://www.fudan.edu.cn/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "shanghai-jiao-tong-university",
        "name_fa": "دانشگاه جیائو تونگ شانگهای",
        "name_en": "Shanghai Jiao Tong University",
        "city": "شانگهای",
        "world_rank": "4",
        "qs_rank_note": "۴۵",
        "website": "https://www.sjtu.edu.cn/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "zhejiang-university",
        "name_fa": "دانشگاه ژجیانگ",
        "name_en": "Zhejiang University",
        "city": "هانگژو",
        "world_rank": "5",
        "qs_rank_note": "۴۴",
        "website": "https://www.zju.edu.cn/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "ustc",
        "name_fa": "دانشگاه علم و فناوری چین",
        "name_en": "University of Science and Technology of China",
        "city": "هفئی",
        "world_rank": "6",
        "qs_rank_note": "۱۳۷",
        "website": "https://www.ustc.edu.cn/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "nanjing-university",
        "name_fa": "دانشگاه نانجینگ",
        "name_en": "Nanjing University",
        "city": "نانجینگ",
        "world_rank": "7",
        "qs_rank_note": "۱۳۳",
        "website": "https://www.nju.edu.cn/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "wuhan-university",
        "name_fa": "دانشگاه ووهان",
        "name_en": "Wuhan University",
        "city": "ووهان",
        "world_rank": "8",
        "qs_rank_note": "۱۹۴",
        "website": "https://www.whu.edu.cn/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "harbin-institute-of-technology",
        "name_fa": "موسسه فناوری هاربین",
        "name_en": "Harbin Institute of Technology",
        "city": "هاربین",
        "world_rank": "9",
        "qs_rank_note": "۲۵۶",
        "website": "https://www.hit.edu.cn/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "xian-jiaotong-university",
        "name_fa": "دانشگاه شی‌آن جیائوتونگ",
        "name_en": "Xi'an Jiaotong University",
        "city": "شی‌آن",
        "world_rank": "10",
        "qs_rank_note": "۲۹۱",
        "website": "https://www.xjtu.edu.cn/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "sun-yat-sen-university",
        "name_fa": "دانشگاه سون یات سن",
        "name_en": "Sun Yat-sen University",
        "city": "گوانگژو",
        "world_rank": "11",
        "qs_rank_note": "۳۲۳",
        "website": "https://www.sysu.edu.cn/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "tongji-university",
        "name_fa": "دانشگاه تونگجی",
        "name_en": "Tongji University",
        "city": "شانگهای",
        "world_rank": "12",
        "qs_rank_note": "۲۱۱",
        "website": "https://www.tongji.edu.cn/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "nankai-university",
        "name_fa": "دانشگاه نانکای",
        "name_en": "Nankai University",
        "city": "تیانجین",
        "world_rank": "13",
        "qs_rank_note": "۳۷۷",
        "website": "https://www.nankai.edu.cn/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "tianjin-university",
        "name_fa": "دانشگاه تیانجین",
        "name_en": "Tianjin University",
        "city": "تیانجین",
        "world_rank": "14",
        "qs_rank_note": "۳۸۵",
        "website": "https://www.tju.edu.cn/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "sichuan-university",
        "name_fa": "دانشگاه سیچوان",
        "name_en": "Sichuan University",
        "city": "چنگدو",
        "world_rank": "15",
        "qs_rank_note": "۳۳۶",
        "website": "https://www.scu.edu.cn/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "shandong-university",
        "name_fa": "دانشگاه شاندونگ",
        "name_en": "Shandong University",
        "city": "جینان",
        "world_rank": "16",
        "qs_rank_note": "۴۰۳",
        "website": "https://www.sdu.edu.cn/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "jilin-university",
        "name_fa": "دانشگاه جیلین",
        "name_en": "Jilin University",
        "city": "چانگچون",
        "world_rank": "17",
        "qs_rank_note": "۴۹۷",
        "website": "https://www.jlu.edu.cn/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "xiamen-university",
        "name_fa": "دانشگاه شیامن",
        "name_en": "Xiamen University",
        "city": "شیامن",
        "world_rank": "18",
        "qs_rank_note": "۳۶۲",
        "website": "https://www.xmu.edu.cn/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "beijing-normal-university",
        "name_fa": "دانشگاه نرمال پکن",
        "name_en": "Beijing Normal University",
        "city": "پکن",
        "world_rank": "19",
        "qs_rank_note": "۲۷۲",
        "website": "https://www.bnu.edu.cn/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "huazhong-university-of-science-and-technology",
        "name_fa": "دانشگاه علوم و فناوری هوآژونگ",
        "name_en": "Huazhong University of Science and Technology",
        "city": "ووهان",
        "world_rank": "20",
        "qs_rank_note": "۲۷۵",
        "website": "https://www.hust.edu.cn/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "beijing-institute-of-technology",
        "name_fa": "موسسه فناوری پکن",
        "name_en": "Beijing Institute of Technology",
        "city": "پکن",
        "world_rank": "21",
        "qs_rank_note": "۱۷۹",
        "website": "https://www.bit.edu.cn/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "beihang-university",
        "name_fa": "دانشگاه بی‌هانگ",
        "name_en": "Beihang University",
        "city": "پکن",
        "world_rank": "22",
        "qs_rank_note": "۴۵۲",
        "website": "https://www.buaa.edu.cn/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "southeast-university-china",
        "name_fa": "دانشگاه جنوب شرق",
        "name_en": "Southeast University",
        "city": "نانجینگ",
        "world_rank": "23",
        "qs_rank_note": "۴۲۸",
        "website": "https://www.seu.edu.cn/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "dalian-university-of-technology",
        "name_fa": "دانشگاه فناوری دالیان",
        "name_en": "Dalian University of Technology",
        "city": "دالیان",
        "world_rank": "24",
        "qs_rank_note": "۴۹۷",
        "website": "https://www.dlut.edu.cn/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "central-south-university",
        "name_fa": "دانشگاه مرکز جنوب",
        "name_en": "Central South University",
        "city": "چانگشا",
        "world_rank": "25",
        "qs_rank_note": "۳۷۶",
        "website": "https://www.csu.edu.cn/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "hunan-university",
        "name_fa": "دانشگاه هونان",
        "name_en": "Hunan University",
        "city": "چانگشا",
        "world_rank": "26",
        "qs_rank_note": "۴۴۸",
        "website": "https://www.hnu.edu.cn/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "east-china-normal-university",
        "name_fa": "دانشگاه نرمال شرق چین",
        "name_en": "East China Normal University",
        "city": "شانگهای",
        "world_rank": "27",
        "qs_rank_note": "۵۳۱",
        "website": "https://www.ecnu.edu.cn/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "chongqing-university",
        "name_fa": "دانشگاه چونگ‌چینگ",
        "name_en": "Chongqing University",
        "city": "چونگ‌چینگ",
        "world_rank": "28",
        "qs_rank_note": "۵۶۱",
        "website": "https://www.cqu.edu.cn/",
        "mo_science": True,
        "mo_health": True,
    },
    {
        "slug": "lanzhou-university",
        "name_fa": "دانشگاه لانژو",
        "name_en": "Lanzhou University",
        "city": "لانژو",
        "world_rank": "29",
        "qs_rank_note": "۷۵۱–۸۰۰",
        "website": "https://www.lzu.edu.cn/",
        "mo_science": True,
        "mo_health": False,
    },
    {
        "slug": "china-agricultural-university",
        "name_fa": "دانشگاه کشاورزی چین",
        "name_en": "China Agricultural University",
        "city": "پکن",
        "world_rank": "30",
        "qs_rank_note": "۸۰۱–۸۵۰",
        "website": "https://www.cau.edu.cn/",
        "mo_science": True,
        "mo_health": False,
    },
]

UNIVERSITY_CATALOG_BY_COUNTRY = {
    "canada": CANADA_UNIVERSITIES,
    "spain": SPAIN_UNIVERSITIES,
    "china": CHINA_UNIVERSITIES,
}

COUNTRY_LABELS = {
    "canada": "کانادا",
    "spain": "اسپانیا",
    "china": "چین",
}
