"""
داده های محتوای غنی کشورها برای StudyCountry های جهانی.
"""

from __future__ import annotations

from typing import Any

from core.study_destinations import WORLD_STUDY_COUNTRY_CODES, WORLD_STUDY_COUNTRY_LABELS


COUNTRY_ENGLISH_NAMES: dict[str, str] = {
    "uk": "United Kingdom",
    "usa": "United States",
    "australia": "Australia",
    "germany": "Germany",
    "italy": "Italy",
    "france": "France",
    "netherlands": "Netherlands",
    "switzerland": "Switzerland",
    "japan": "Japan",
    "south_korea": "South Korea",
    "singapore": "Singapore",
    "hong_kong": "Hong Kong",
    "ireland": "Ireland",
    "sweden": "Sweden",
    "belgium": "Belgium",
    "austria": "Austria",
    "new_zealand": "New Zealand",
    "denmark": "Denmark",
    "finland": "Finland",
    "norway": "Norway",
    "portugal": "Portugal",
    "poland": "Poland",
    "czech": "Czech Republic",
    "hungary": "Hungary",
    "greece": "Greece",
    "turkey": "Turkey",
    "malaysia": "Malaysia",
    "uae": "United Arab Emirates",
    "saudi_arabia": "Saudi Arabia",
    "qatar": "Qatar",
    "india": "India",
    "thailand": "Thailand",
    "israel": "Israel",
    "brazil": "Brazil",
    "mexico": "Mexico",
    "argentina": "Argentina",
    "chile": "Chile",
    "south_africa": "South Africa",
    "egypt": "Egypt",
    "russia": "Russia",
    "taiwan": "Taiwan",
}


DEFAULT_DEGREES: list[tuple[str, str, str]] = [
    ("کارشناسی", "۳ تا ۴ سال", "اغلب نیازمند مدرک زبان و دیپلم معتبر"),
    ("کارشناسی ارشد", "۱ تا ۲ سال", "تمرکز بالا روی پروپوزال یا رزومه آکادمیک"),
    ("دکتری", "۳ تا ۵ سال", "عموما مبتنی بر استاد راهنما و پروژه پژوهشی"),
]

DEFAULT_ADMISSION_STEPS: list[str] = [
    "انتخاب رشته و ۵ تا ۱۰ دانشگاه متناسب با بودجه و رزومه",
    "آماده سازی زبان، رزومه، SOP و توصیه نامه",
    "ثبت درخواست در پرتال دانشگاه یا سیستم ملی",
    "پیگیری مدارک تکمیلی، مصاحبه یا آزمون ورودی (در صورت نیاز)",
    "دریافت پذیرش، پرداخت دپازیت و آماده سازی ویزا",
    "رزرو خوابگاه یا محل سکونت و برنامه سفر",
]

DEFAULT_LANG_REQUIREMENTS: list[tuple[str, str]] = [
    ("کارشناسی", "IELTS 6.0 تا 6.5 یا معادل"),
    ("کارشناسی ارشد", "IELTS 6.5 تا 7.0 یا معادل"),
    ("دکتری", "مدرک زبان + تایید استاد/گروه پژوهشی"),
]

DEFAULT_DOCS: list[str] = [
    "پاسپورت معتبر",
    "مدارک تحصیلی و ریزنمرات ترجمه شده",
    "مدرک زبان معتبر",
    "رزومه و انگیزه نامه",
    "تمکن مالی و گردش حساب",
    "بیمه درمانی دانشجویی",
]


def _default_pathway_steps(country_name: str) -> dict[int, str]:
    return {
        1: "<p><strong>مرحله ۱ - ارزیابی اولیه:</strong> معدل، گپ تحصیلی، بودجه و هدف شما بررسی می شود.</p>",
        2: f"<p><strong>مرحله ۲ - انتخاب مسیر {country_name}:</strong> دانشگاه، شهر و مقطع مناسب نهایی می شود.</p>",
        3: "<p><strong>مرحله ۳ - آماده سازی مدارک:</strong> ترجمه رسمی، رزومه، SOP و توصیه نامه تکمیل می شود.</p>",
        4: "<p><strong>مرحله ۴ - ارسال اپلای:</strong> فرم ها ثبت و وضعیت پرونده به صورت زمان بندی شده پیگیری می شود.</p>",
        5: "<p><strong>مرحله ۵ - ویزا و تمکن:</strong> مدارک سفارت، تمکن و پرداخت ها آماده می شود.</p>",
        6: "<p><strong>مرحله ۶ - پیش از سفر:</strong> خوابگاه، بلیت، بیمه و چک لیست ورود بسته می شود.</p>",
        7: "<p><strong>مرحله ۷ - استقرار:</strong> ثبت نام نهایی دانشگاه و شروع زندگی دانشجویی انجام می شود.</p>",
    }


def _default_visa_sections(country_name: str) -> list[tuple[str, str]]:
    return [
        (
            "مدارک کلیدی ویزا",
            "<ul>"
            "<li>نامه پذیرش رسمی دانشگاه یا موسسه آموزشی</li>"
            "<li>گذرنامه معتبر و فرم درخواست کامل</li>"
            "<li>مدرک تمکن مالی و پوشش هزینه های سال اول</li>"
            "<li>بیمه درمانی معتبر و رسید پرداخت های الزامی</li>"
            "</ul>",
        ),
        (
            "نکات مصاحبه و بررسی پرونده",
            f"<ul>"
            f"<li>هدف تحصیلی و برنامه بازگشت/مسیر شغلی را شفاف توضیح دهید.</li>"
            f"<li>همخوانی رشته، سابقه و انتخاب {country_name} را دقیق بیان کنید.</li>"
            f"<li>مبنای تامین مالی و بودجه زندگی را با اعداد واقعی ارائه دهید.</li>"
            f"</ul>",
        ),
    ]


def _default_image_queries(code: str) -> list[str]:
    en_name = COUNTRY_ENGLISH_NAMES.get(code, code)
    return [
        f"{en_name} university campus students",
        f"{en_name} student visa office building",
        f"{en_name} city skyline public transport",
    ]


RAW_WORLD_FACTS: dict[str, dict[str, Any]] = {
    "uk": {
        "hook": "با دانشگاه های قدیمی، رتبه جهانی قوی و شبکه کاری بین المللی شناخته می شود.",
        "intl_students": "حدود ۷۵۰ هزار",
        "cities": [("لندن", "شبکه کاری و فرصت کارآموزی بالا"), ("منچستر", "هزینه متعادل تر و دانشگاه های قوی")],
        "popular_fields": ["مدیریت", "علوم داده", "حقوق", "مهندسی", "روان شناسی"],
        "language_note": "اکثر برنامه ها انگلیسی هستند و برای بعضی رشته ها مصاحبه آنلاین برگزار می شود.",
        "visa_name": "Student visa (UK)",
        "visa_finance": "برای سال اول: شهریه + هزینه زندگی. برای لندن ماهانه £1,529 و خارج لندن ماهانه £1,171 (تا ۹ ماه) معیار رسمی است.",
        "work_rights": "عموما تا ۲۰ ساعت در هفته طی ترم و تمام وقت در تعطیلات.",
        "post_study": "Graduate Route معمولا تا ۲ سال (و برای دکتری ۳ سال) اجازه ماندن و کار می دهد.",
        "official_visa_url": "https://www.gov.uk/student-visa",
        "deadlines": "برای سپتامبر بهتر است بین آبان تا اردیبهشت اپلای انجام شود؛ بعضی رشته ها زودتر بسته می شوند.",
        "living_costs": [("لندن", "£1,400 تا £1,900", "وابسته به خوابگاه و حمل ونقل"), ("شهرهای خارج لندن", "£850 تا £1,250", "دانشجویی مقرون به صرفه تر")],
        "tuition": [("کارشناسی", "£13,000 تا £24,000"), ("ارشد", "£15,000 تا £32,000")],
        "housing_note": "رزرو خوابگاه دانشگاهی را بلافاصله بعد از دریافت CAS شروع کنید.",
        "scholarships": [("Chevening", "بورسیه کامل رقابتی برای مقطع ارشد"), ("GREAT Scholarships", "کمک هزینه مشترک دانشگاه ها و British Council")],
        "pros": ["مدرک معتبر جهانی", "دوره های ارشد کوتاه تر", "امکان کار پس از تحصیل"],
        "cons": ["هزینه بالای لندن", "رقابت بالا برای بورسیه کامل"],
        "pathway_duration": "۸ تا ۱۴ ماه",
        "pathway_stats": [("زمان اخذ پذیرش", "۶ تا ۱۲ هفته"), ("زمان ویزا", "۳ تا ۸ هفته"), ("حق کار", "۲۰ ساعت/هفته"), ("هزینه زندگی", "£1,171 تا £1,529 ماهانه معیار")],
        "headline": "تحصیل در انگلستان ۲۰۲۶؛ پذیرش، ویزا و هزینه ها برای ایرانی ها",
        "search_keywords": "تحصیل در انگلستان, Student visa UK, دانشگاه های انگلیس, هزینه زندگی لندن",
        "meta_title": "تحصیل در انگلستان ۲۰۲۶ | ویزا، پذیرش و هزینه زندگی",
        "image_queries": ["United Kingdom university campus", "UKVI student visa center", "London student life underground"],
    },
    "usa": {
        "hook": "بزرگ ترین اکوسیستم دانشگاهی دنیا با تنوع رشته و فرصت پژوهشی گسترده دارد.",
        "intl_students": "بیش از ۱ میلیون",
        "cities": [("بوستون", "قطب دانشگاهی و پژوهشی"), ("آستین", "تکنولوژی و هزینه متعادل تر نسبت به سواحل")],
        "popular_fields": ["علوم کامپیوتر", "مهندسی", "بیزنس", "علوم زیستی", "فیلم و هنر"],
        "language_note": "علاوه بر زبان، بسیاری از برنامه ها به GRE/GMAT یا الزامات دپارتمان نیاز دارند.",
        "visa_name": "F-1 Student Visa",
        "visa_finance": "اثبات توان پرداخت شهریه سال اول + هزینه زندگی طبق I-20 ضروری است.",
        "work_rights": "کار داخل دانشگاه تا ۲۰ ساعت در هفته؛ کار بیرون دانشگاه با مجوزهای CPT/OPT.",
        "post_study": "OPT تا ۱۲ ماه و برای رشته های STEM تا ۳۶ ماه قابل افزایش است.",
        "official_visa_url": "https://travel.state.gov/content/travel/en/us-visas/study/student-visa.html",
        "deadlines": "ددلاین های Fall اغلب از آذر تا بهمن هستند؛ برای فاند کامل باید خیلی زودتر اقدام شود.",
        "living_costs": [("شهرهای گران (NY/CA)", "$1,600 تا $2,500", "وابسته به خوابگاه و بیمه"), ("شهرهای متوسط", "$900 تا $1,500", "هزینه مناسب تر")],
        "tuition": [("دانشگاه دولتی", "$18,000 تا $35,000"), ("دانشگاه خصوصی", "$30,000 تا $60,000+")],
        "housing_note": "Off-campus نیازمند ضامن یا پیش پرداخت بالاتر است؛ گزینه خوابگاه برای ترم اول امن تر است.",
        "scholarships": [("Assistantship", "فاند RA/TA به ویژه در دکتری"), ("Merit Scholarship", "تخفیف شهریه مبتنی بر رزومه")],
        "pros": ["تنوع دانشگاه و رشته", "بازار کار پویا", "امکان OPT ویژه STEM"],
        "cons": ["نوسان هزینه ها بالا", "فرایند ویزا حساس و نیازمند برنامه شفاف"],
        "pathway_duration": "۱۰ تا ۱۸ ماه",
        "pathway_stats": [("آمادگی آزمون", "۲ تا ۶ ماه"), ("پاسخ پذیرش", "۸ تا ۱۶ هفته"), ("حق کار", "On-campus/CPT/OPT"), ("شانس فاند", "بالاتر در پژوهش محور")],
        "headline": "تحصیل در آمریکا؛ مسیر اپلای F-1، فاند و کار پس از تحصیل",
        "search_keywords": "تحصیل در آمریکا, ویزای F1, اپلای آمریکا, OPT STEM",
        "image_queries": ["United States university quad", "US embassy visa interview hall", "Boston student neighborhood"],
    },
    "australia": {
        "hook": "با دانشگاه های تحقیقاتی قوی و سیستم مهاجرتی شفاف، مقصد محبوب دانشجویان بین المللی است.",
        "intl_students": "بیش از ۷۰۰ هزار",
        "cities": [("ملبورن", "دانشگاه های معتبر و زندگی فرهنگی"), ("بریزبن", "هزینه پایین تر از سیدنی")],
        "popular_fields": ["پرستاری", "مهندسی", "IT", "مدیریت پروژه", "علوم محیط زیست"],
        "language_note": "اکثر برنامه ها انگلیسی هستند؛ بعضی رشته های سلامت به نمره زبان بالاتر نیاز دارند.",
        "visa_name": "Student Visa (Subclass 500)",
        "visa_finance": "طبق معیار ۲۰۲۵-۲۰۲۶ هزینه زندگی سالانه دانشجو AUD 29,710 در ارزیابی مالی لحاظ می شود.",
        "work_rights": "معمولا ۴۸ ساعت در هر دو هفته طی ترم و تمام وقت در تعطیلات رسمی.",
        "post_study": "Temporary Graduate (subclass 485) بسته به مقطع و شهر ۲ تا ۴ سال.",
        "official_visa_url": "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500",
        "deadlines": "ورودی های اصلی فوریه و جولای است؛ برای COE و ویزا حداقل ۴ تا ۶ ماه زمان بگذارید.",
        "living_costs": [("سیدنی/ملبورن", "AUD 1,800 تا 2,700", "اجاره سهم بزرگی از هزینه است"), ("بریزبن/آدلاید", "AUD 1,300 تا 2,000", "مناسب تر برای بودجه متوسط")],
        "tuition": [("کارشناسی", "AUD 24,000 تا 45,000"), ("ارشد", "AUD 26,000 تا 50,000")],
        "housing_note": "پیش از ورود، گزینه های Purpose-built student accommodation را با حمل ونقل مقایسه کنید.",
        "scholarships": [("Australia Awards", "بورسیه رقابتی دولتی"), ("Destination Australia", "کمک هزینه برای دانشگاه های مناطق کم تراکم")],
        "pros": ["زبان انگلیسی", "کیفیت زندگی بالا", "مسیر کاری پس از تحصیل"],
        "cons": ["شهریه و اجاره نسبتا بالا", "ظرفیت محدود خوابگاه در شهرهای بزرگ"],
        "pathway_duration": "۹ تا ۱۵ ماه",
        "pathway_stats": [("COE تا ویزا", "۴ تا ۱۰ هفته"), ("تمکن مرجع", "AUD 29,710 سالانه"), ("حق کار", "۴۸ ساعت/۲ هفته"), ("PG Work", "۲ تا ۴ سال")],
        "headline": "تحصیل در استرالیا ۲۰۲۶؛ ویزا، هزینه واقعی و کار دانشجویی",
        "image_queries": ["Australia university campus Melbourne", "Australian student visa document", "Sydney student accommodation district"],
    },
    "germany": {
        "hook": "با شهریه پایین دانشگاه های دولتی و صنعت مهندسی قوی، گزینه بسیار محبوب ایرانی هاست.",
        "intl_students": "حدود ۴۶۰ هزار",
        "cities": [("برلین", "استارتاپ و تنوع دانشگاهی"), ("مونیخ", "مهندسی قوی و بازار کار صنعتی")],
        "popular_fields": ["مهندسی مکانیک", "مهندسی برق", "علوم کامپیوتر", "مدیریت", "معماری"],
        "language_note": "برنامه های انگلیسی در ارشد زیاد است اما برای زندگی روزمره دانستن آلمانی مزیت مهمی است.",
        "visa_finance": "تمکن اصلی دانشجویی معمولا از طریق Blocked Account با مبلغ €11,904 برای سال اول اثبات می شود.",
        "work_rights": "۱۲۰ روز کامل یا ۲۴۰ نیم روز در سال (طبق قوانین دانشجویی).",
        "post_study": "پس از فارغ التحصیلی معمولا ۱۸ ماه فرصت جستجوی کار داده می شود.",
        "official_visa_url": "https://www.make-it-in-germany.com/en/visa-residence/types/studying",
        "deadlines": "ترم زمستان: عمدتا تا جولای؛ ترم تابستان: تا ژانویه (بسته به دانشگاه متفاوت است).",
        "living_costs": [("مونیخ/هامبورگ", "€1,100 تا €1,600", "اجاره بالا"), ("برلین/لایپزیگ", "€850 تا €1,250", "تنوع بیشتر خوابگاه و WG")],
        "tuition": [("دانشگاه دولتی", "اغلب بدون شهریه + Semester fee"), ("دانشگاه خصوصی", "€8,000 تا €25,000")],
        "housing_note": "در شهرهای بزرگ، همزمان با اپلای برای خوابگاه Studentenwerk ثبت نام کنید.",
        "scholarships": [("DAAD", "انواع کمک هزینه پژوهشی و تحصیلی"), ("Deutschlandstipendium", "حمایت مشترک دانشگاه و حامیان")],
        "pros": ["هزینه تحصیل پایین در دولتی", "صنعت قوی و بازار کار مهندسی", "موقعیت خوب در اروپا"],
        "cons": ["رقابت بالا برای خوابگاه", "بروکراسی اداری زمان بر"],
        "pathway_duration": "۸ تا ۱۴ ماه",
        "pathway_stats": [("Blocked Account", "€11,904"), ("ویزا", "۴ تا ۱۲ هفته"), ("حق کار", "۱۲۰ روز کامل"), ("شهریه دولتی", "عموما نزدیک صفر")],
        "headline": "تحصیل در آلمان؛ راهنمای ویزا، بلوکه اکانت و پذیرش ۲۰۲۶",
        "search_keywords": "تحصیل در آلمان, blocked account 11904, ویزای دانشجویی آلمان, دانشگاه دولتی آلمان",
        "image_queries": ["Germany university lecture hall", "German blocked account documents", "Berlin student bicycle city"],
    },
    "italy": {
        "hook": "ترکیبی از دانشگاه های قدیمی، هزینه منطقی و بورسیه های منطقه ای را ارائه می دهد.",
        "intl_students": "حدود ۱۰۰ هزار",
        "cities": [("میلان", "بازار کار طراحی و بیزنس"), ("بولونیا", "دانشگاه تاریخی و دانشجویی")],
        "popular_fields": ["طراحی", "معماری", "مهندسی", "اقتصاد", "علوم غذایی"],
        "language_note": "برنامه های انگلیسی در ارشد زیاد شده اما دانستن ایتالیایی برای کار پاره وقت مهم است.",
        "official_visa_url": "https://vistoperitalia.esteri.it/home/en",
        "living_costs": [("میلان/رم", "€900 تا €1,500", "بستگی زیاد به اجاره"), ("تورین/پادوا", "€700 تا €1,100", "گزینه اقتصادی تر")],
        "tuition": [("دولتی", "€900 تا €4,000"), ("خصوصی", "€8,000 تا €20,000+")],
        "scholarships": [("DSU/EDISU", "بورسیه منطقه ای با کمک هزینه نقدی و خوابگاه"), ("Invest Your Talent", "بورسیه محدود برای رشته های منتخب")],
        "pros": ["بورسیه منطقه ای مناسب", "فرهنگ دانشجویی قوی", "هزینه متوسط نسبت به اروپای غربی"],
        "cons": ["نوسان زمان صدور ویزا", "نیاز به پیگیری زیاد برای مدارک اداری"],
        "image_queries": ["Italy university courtyard", "Italian consulate student visa", "Milan tram student district"],
    },
    "france": {
        "hook": "با دانشگاه های معتبر، شهریه دولتی قابل قبول و اکوسیستم تحقیقاتی قوی شناخته می شود.",
        "intl_students": "حدود ۴۰۰ هزار",
        "cities": [("پاریس", "شبکه علمی گسترده ولی گران"), ("لیون", "کیفیت خوب با هزینه متعادل تر")],
        "popular_fields": ["مدیریت", "مهندسی", "هوش مصنوعی", "هنر", "علوم سیاسی"],
        "language_note": "برنامه های انگلیسی رو به افزایش است اما برای ادغام اجتماعی، فرانسه بسیار مهم است.",
        "official_visa_url": "https://france-visas.gouv.fr/en/web/france-visas/student",
        "living_costs": [("پاریس", "€1,200 تا €1,900", "بالاترین هزینه در فرانسه"), ("شهرهای دیگر", "€750 تا €1,200", "خوابگاه CROUS کمک می کند")],
        "tuition": [("دانشگاه دولتی", "تقریبا €2,800 تا €3,900 برای بین المللی"), ("Grandes Ecoles", "€8,000 تا €35,000")],
        "scholarships": [("Eiffel Excellence", "بورسیه رقابتی برای ارشد/دکتری"), ("Bourses du gouvernement francais", "طرح های دولتی متنوع")],
        "pros": ["کیفیت آموزش بالا", "شهریه دولتی قابل مدیریت", "فرصت های پژوهشی خوب"],
        "cons": ["بروکراسی اقامت", "رقابت بالا در شهرهای بزرگ"],
        "image_queries": ["France university amphitheatre", "France student visa office", "Lyon student riverside"],
    },
    "netherlands": {
        "hook": "به خاطر برنامه های انگلیسی فراوان و ارتباط نزدیک دانشگاه با صنعت شناخته می شود.",
        "intl_students": "بیش از ۱۲۰ هزار",
        "cities": [("آمستردام", "بین المللی و پویا"), ("آیندهوون", "فناوری و مهندسی")],
        "popular_fields": ["علوم داده", "مهندسی", "طراحی", "مدیریت زنجیره تامین", "کشاورزی"],
        "language_note": "اغلب برنامه ها به انگلیسی ارائه می شود اما یادگیری هلندی برای کار مفید است.",
        "official_visa_url": "https://ind.nl/en/residence-permits/study/student-residence-permit-for-university-or-higher-professional-education",
        "living_costs": [("آمستردام/اوترخت", "€1,200 تا €1,800", "کمبود مسکن دانشجویی"), ("شهرهای کوچک تر", "€900 تا €1,300", "پیدا کردن اتاق آسان تر")],
        "tuition": [("EU/EEA", "پایین تر"), ("Non-EU", "€8,000 تا €25,000")],
        "housing_note": "پیش از دریافت ویزا برای اتاق دانشجویی اقدام کنید؛ کمبود مسکن جدی است.",
        "scholarships": [("NL Scholarship", "کمک هزینه اولیه برای دانشجویان غیراروپایی"), ("University-specific grants", "تخفیف شهریه دانشگاهی")],
        "pros": ["برنامه انگلیسی زیاد", "کیفیت آموزشی بالا", "محیط بین المللی"],
        "cons": ["بحران مسکن دانشجویی", "هزینه زندگی نسبتا بالا"],
        "image_queries": ["Netherlands technical university campus", "Dutch residence permit student", "Amsterdam student biking"],
    },
    "switzerland": {
        "hook": "دانشگاه های پژوهشی سطح بالا و بازار کار تخصصی با درآمد مناسب دارد.",
        "intl_students": "حدود ۷۰ هزار",
        "cities": [("زوریخ", "فناوری و فایننس"), ("لوزان", "پژوهش و مهندسی")],
        "popular_fields": ["مهندسی", "علوم کامپیوتر", "فایننس", "هتلداری", "علوم پایه"],
        "language_note": "برنامه ها بسته به کانتون به انگلیسی/آلمانی/فرانسه ارائه می شوند.",
        "official_visa_url": "https://www.sem.admin.ch/sem/en/home/themen/einreise/faq.html",
        "living_costs": [("زوریخ/ژنو", "CHF 1,800 تا CHF 2,800", "از گران ترین شهرهای اروپا"), ("شهرهای دانشجویی کوچک", "CHF 1,400 تا CHF 2,100", "کمی مقرون به صرفه تر")],
        "tuition": [("دانشگاه دولتی", "CHF 1,000 تا CHF 4,000"), ("خصوصی", "CHF 15,000 تا CHF 40,000+")],
        "scholarships": [("Swiss Government Excellence", "بورسیه پژوهشی مقطع تکمیلی"), ("EPFL/ETH funding", "گرنت و دستیار پژوهشی")],
        "pros": ["کیفیت علمی ممتاز", "امنیت و کیفیت زندگی بسیار بالا", "بازار کار تخصصی"],
        "cons": ["هزینه زندگی بسیار بالا", "رقابت شدید پذیرش در دانشگاه های برتر"],
        "image_queries": ["Switzerland university lab", "Swiss student visa permit office", "Zurich student tram"],
    },
    "japan": {
        "hook": "ترکیبی از فناوری پیشرفته، نظم بالا و دانشگاه های پژوهشی معتبر را ارائه می دهد.",
        "intl_students": "حدود ۳۰۰ هزار",
        "cities": [("توکیو", "فرصت های گسترده علمی و صنعتی"), ("اوزاکا", "هزینه پایین تر از توکیو")],
        "popular_fields": ["رباتیک", "مهندسی", "طراحی صنعتی", "علوم مواد", "کسب وکار"],
        "language_note": "برنامه های انگلیسی وجود دارد اما برای کار و زندگی روزمره، ژاپنی مزیت مهمی است.",
        "official_visa_url": "https://www.moj.go.jp/isa/applications/status/student.html?hl=en",
        "living_costs": [("توکیو", "JPY 120,000 تا 180,000", "اجاره و حمل ونقل بالا"), ("شهرهای دیگر", "JPY 80,000 تا 130,000", "به صرفه تر")],
        "tuition": [("ملی/دولتی", "JPY 535,800 تقریبی سالانه"), ("خصوصی", "JPY 800,000 تا 1,800,000")],
        "scholarships": [("MEXT", "بورسیه دولتی معروف ژاپن"), ("JASSO", "کمک هزینه های ماهانه محدود")],
        "pros": ["فناوری و پژوهش قوی", "امنیت بالا", "فرهنگ کاری منظم"],
        "cons": ["مانع زبان در خارج دانشگاه", "فشار در برخی برنامه ها بالا"],
        "image_queries": ["Japan university campus spring", "Japan student visa residence card", "Tokyo student commuter train"],
    },
    "south_korea": {
        "hook": "با رشد سریع فناوری، دانشگاه های قوی و بورسیه های دولتی گزینه جذابی است.",
        "intl_students": "حدود ۲۰۰ هزار",
        "cities": [("سئول", "بزرگ ترین مرکز دانشگاهی"), ("دائجون", "تمرکز پژوهشی و هزینه کمتر")],
        "popular_fields": ["مهندسی", "IT", "طراحی", "بایوتک", "مطالعات کره"],
        "language_note": "برنامه های انگلیسی موجود است اما دانستن کره ای برای کار پاره وقت ارزشمند است.",
        "official_visa_url": "https://www.visa.go.kr/openPage.do?MENU_ID=10106",
        "living_costs": [("سئول", "KRW 1,100,000 تا 1,800,000", "اجاره بالا"), ("شهرهای دیگر", "KRW 800,000 تا 1,300,000", "مقرون به صرفه تر")],
        "tuition": [("کارشناسی/ارشد", "KRW 4,000,000 تا 12,000,000 سالانه")],
        "scholarships": [("GKS", "بورسیه دولتی کامل کره"), ("University Tuition Waiver", "تخفیف شهریه براساس معدل")],
        "pros": ["بورسیه دولتی خوب", "دانشگاه های تکنولوژی قوی", "زندگی شهری پویا"],
        "cons": ["رقابت آموزشی بالا", "فشار زبان در بازار کار"],
        "image_queries": ["South Korea university campus", "Korea student visa issuance", "Seoul student district"],
    },
    "singapore": {
        "hook": "آموزش انگلیسی با کیفیت بالا و پیوند نزدیک با بازار کار آسیا را فراهم می کند.",
        "intl_students": "حدود ۷۰ هزار",
        "cities": [("سنگاپور", "شهر-کشور یکپارچه با حمل ونقل عالی"), ("Jurong", "نزدیک به هاب صنعتی و پژوهشی")],
        "popular_fields": ["فایننس", "علوم کامپیوتر", "مهندسی", "Logistics", "Data Analytics"],
        "language_note": "زبان آموزشی عمدتا انگلیسی است و محیط بین المللی بسیار قوی دارد.",
        "official_visa_url": "https://www.ica.gov.sg/reside/STP",
        "living_costs": [("مرکز شهر", "SGD 1,800 تا 2,800", "هزینه مسکن بالا"), ("حومه", "SGD 1,300 تا 2,000", "صرفه جویی بهتر")],
        "tuition": [("دانشگاه دولتی", "SGD 17,000 تا 40,000"), ("خصوصی", "SGD 20,000 تا 45,000")],
        "scholarships": [("SINGA", "بورسیه پژوهشی برای دکتری"), ("NUS/NTU Grants", "گرنت و کمک شهریه")],
        "pros": ["زبان انگلیسی", "امنیت و نظم بالا", "ارتباط قوی با صنعت"],
        "cons": ["هزینه مسکن بالا", "رقابت شدید پذیرش"],
        "image_queries": ["Singapore university campus", "Singapore ICA student pass", "Singapore student housing block"],
    },
    "hong_kong": {
        "hook": "قطب مالی و آموزشی آسیا با دانشگاه های رتبه بالا و برنامه های انگلیسی است.",
        "intl_students": "حدود ۵۰ هزار",
        "cities": [("Kowloon", "دانشگاه های مهم و دسترسی عالی"), ("Hong Kong Island", "شبکه کاری و مالی قوی")],
        "popular_fields": ["فایننس", "بیزنس", "مهندسی", "AI", "حقوق تجارت"],
        "language_note": "بسیاری از برنامه ها انگلیسی هستند؛ کانتونی برای زندگی روزمره مفید است.",
        "official_visa_url": "https://www.immd.gov.hk/eng/services/visas/study.html",
        "living_costs": [("مرکزی", "HKD 9,000 تا 15,000", "اجاره بالا"), ("اشتراکی/خوابگاه", "HKD 5,500 تا 9,000", "به صرفه تر")],
        "tuition": [("دانشگاه های اصلی", "HKD 120,000 تا 220,000 سالانه")],
        "scholarships": [("HKSAR Scholarships", "حمایت تحصیلی محدود"), ("University Merit Awards", "بورسیه براساس شایستگی")],
        "pros": ["دانشگاه های معتبر", "بازار کار بین المللی", "دسترسی به آسیا"],
        "cons": ["اجاره بالا", "فشار رقابتی زیاد"],
        "image_queries": ["Hong Kong university tower", "Hong Kong study visa office", "Hong Kong tram students"],
    },
    "ireland": {
        "hook": "مقصد انگلیسی زبان اروپایی با حضور شرکت های بزرگ فناوری و داروسازی است.",
        "intl_students": "حدود ۴۰ هزار",
        "cities": [("دوبلین", "مرکز فناوری و شرکت های بین المللی"), ("کورک", "محیط آرام تر و دانشگاه های خوب")],
        "popular_fields": ["Data Science", "داروسازی", "فایننس", "مهندسی نرم افزار", "Business Analytics"],
        "language_note": "زبان اصلی آموزش انگلیسی است و مسیر ارتباط با کارفرما نسبتا روشن است.",
        "official_visa_url": "https://www.irishimmigration.ie/coming-to-study-in-ireland/",
        "living_costs": [("دوبلین", "EUR 1,200 تا 1,900", "هزینه اجاره بالا"), ("شهرهای دیگر", "EUR 850 تا 1,300", "مدیریت پذیرتر")],
        "tuition": [("کارشناسی", "EUR 10,000 تا 25,000"), ("ارشد", "EUR 12,000 تا 35,000")],
        "scholarships": [("Government of Ireland", "بورسیه رقابتی مقطع تکمیلی"), ("University Scholarships", "تخفیف شهریه محدود")],
        "pros": ["کشور انگلیسی زبان در اتحادیه اروپا", "بازار کار تکنولوژی مناسب", "فرآیند نسبتا شفاف"],
        "cons": ["کمبود مسکن در دوبلین", "شهریه متوسط رو به بالا"],
        "image_queries": ["Ireland university campus green", "Ireland student immigration office", "Dublin student housing"],
    },
    "sweden": {
        "hook": "آموزش پژوهش محور، نوآوری بالا و تمرکز جدی بر پایداری محیطی دارد.",
        "intl_students": "حدود ۴۰ هزار",
        "cities": [("استکهلم", "فرصت های استارتاپی"), ("لوند", "شهر دانشجویی کلاسیک")],
        "popular_fields": ["مهندسی", "طراحی", "علوم محیط زیست", "AI", "Business"],
        "language_note": "بیشتر برنامه های ارشد به انگلیسی است؛ سوئدی برای بازار کار مزیت ایجاد می کند.",
        "official_visa_url": "https://www.migrationsverket.se/English/Private-individuals/Studying-in-Sweden.html",
        "living_costs": [("استکهلم", "SEK 10,000 تا 15,000", "اجاره و غذا بالا"), ("شهرهای کوچک", "SEK 8,000 تا 12,000", "مقرون به صرفه تر")],
        "tuition": [("Non-EU", "SEK 80,000 تا 180,000 سالانه")],
        "scholarships": [("Swedish Institute Scholarships", "بورسیه کامل محدود"), ("University Tuition Waivers", "تخفیف شهریه")],
        "pros": ["کیفیت آموزشی بالا", "محیط نوآوری قوی", "زندگی ایمن"],
        "cons": ["هزینه زندگی بالا", "هوای سرد و زمستان طولانی"],
        "image_queries": ["Sweden university winter campus", "Sweden residence permit student", "Stockholm student metro"],
    },
    "belgium": {
        "hook": "به دلیل حضور نهادهای اروپایی و دانشگاه های قوی چندزبانه، انتخابی کاربردی است.",
        "intl_students": "حدود ۶۰ هزار",
        "cities": [("بروکسل", "شبکه بین المللی و فرصت کارآموزی"), ("لوون", "دانشگاه پژوهش محور")],
        "popular_fields": ["علوم سیاسی", "روابط بین الملل", "مهندسی", "Economics", "Public Health"],
        "language_note": "برنامه ها به انگلیسی/فرانسوی/هلندی ارائه می شوند؛ بسته به منطقه دانشگاه.",
        "official_visa_url": "https://dofi.ibz.be/en/themes/third-country-nationals/study",
        "living_costs": [("بروکسل", "EUR 950 تا 1,450", "اجاره متوسط رو به بالا"), ("سایر شهرها", "EUR 800 تا 1,200", "تعادل بهتر")],
        "tuition": [("دانشگاه دولتی", "EUR 2,500 تا 8,000"), ("مدارس خاص", "تا EUR 15,000+")],
        "scholarships": [("ARES", "بورسیه های محدود برای کشورهای هدف"), ("VLIR-UOS", "برخی برنامه های توسعه محور")],
        "pros": ["دسترسی عالی به اروپا", "دانشگاه های معتبر", "چندزبانه بودن"],
        "cons": ["تنوع قوانین منطقه ای", "بازار مسکن رقابتی در بروکسل"],
        "image_queries": ["Belgium university library", "Belgium student visa office", "Brussels student square"],
    },
    "austria": {
        "hook": "با کیفیت آموزشی خوب و هزینه منطقی در قلب اروپا، مقصدی متعادل برای ایرانی هاست.",
        "intl_students": "حدود ۹۰ هزار",
        "cities": [("وین", "دانشگاه های متنوع و کیفیت زندگی بالا"), ("گراتس", "دانشگاهی و آرام تر")],
        "popular_fields": ["موسیقی و هنر", "مهندسی", "روان شناسی", "Economics", "علوم پایه"],
        "language_note": "برنامه های انگلیسی در ارشد بیشتر است اما آلمانی برای زندگی روزمره مهم است.",
        "official_visa_url": "https://www.oead.at/en/to-austria/entry-and-residence/visa-d",
        "living_costs": [("وین", "EUR 1,000 تا 1,500", "وابسته به اجاره"), ("شهرهای دیگر", "EUR 800 تا 1,200", "مناسب تر")],
        "tuition": [("دانشگاه دولتی", "تقریبا EUR 1,500 تا 3,000 سالانه برای غیراروپایی"), ("خصوصی", "EUR 8,000 تا 25,000")],
        "scholarships": [("OeAD Grants", "حمایت های متنوع دانشجویی"), ("University Excellence", "تخفیف شهریه یا گرنت")],
        "pros": ["کیفیت زندگی بالا", "هزینه متعادل نسبت به اروپای غربی", "موقعیت جغرافیایی مناسب"],
        "cons": ["نیاز به آلمانی برای ادغام بهتر", "ظرفیت محدود خوابگاه دولتی"],
        "image_queries": ["Austria university campus Vienna", "Austria student residence permit", "Vienna student tram"],
    },
    "new_zealand": {
        "hook": "محیط امن، سیستم آموزشی انگلیسی و رویکرد کاربردی در یادگیری دارد.",
        "intl_students": "حدود ۷۰ هزار",
        "cities": [("اوکلند", "بزرگ ترین بازار کار"), ("ولینگتون", "محیط دانشجویی و خلاق")],
        "popular_fields": ["کشاورزی", "IT", "مهندسی", "مدیریت", "علوم محیطی"],
        "language_note": "زبان آموزش انگلیسی است و برای ورود به بازار کار باید مهارت مکالمه قوی داشته باشید.",
        "official_visa_url": "https://www.immigration.govt.nz/new-zealand-visas/visas/visa/fee-paying-student-visa",
        "living_costs": [("اوکلند", "NZD 1,700 تا 2,500", "اجاره قابل توجه"), ("شهرهای کوچک تر", "NZD 1,300 تا 2,000", "هزینه متعادل تر")],
        "tuition": [("کارشناسی", "NZD 22,000 تا 35,000"), ("ارشد", "NZD 26,000 تا 45,000")],
        "scholarships": [("New Zealand Scholarships", "بورسیه های محدود دولتی"), ("University International Scholarships", "تخفیف شهریه")],
        "pros": ["امنیت بالا", "زبان انگلیسی", "تعادل خوب کیفیت/سبک زندگی"],
        "cons": ["فاصله جغرافیایی زیاد", "هزینه پرواز و سفر بالا"],
        "image_queries": ["New Zealand university campus", "New Zealand student visa process", "Auckland student apartments"],
    },
    "denmark": {
        "hook": "مدل آموزشی پروژه محور و ارتباط نزدیک با صنعت اسکاندیناوی را ارائه می دهد.",
        "intl_students": "حدود ۳۵ هزار",
        "cities": [("کپنهاگ", "قطب فناوری و طراحی"), ("آرهوس", "دانشگاهی و متعادل تر")],
        "popular_fields": ["طراحی", "مهندسی", "Business", "Life Sciences", "معماری"],
        "language_note": "اغلب برنامه های ارشد انگلیسی اند؛ دانمارکی برای شغل بلندمدت مهم می شود.",
        "official_visa_url": "https://www.nyidanmark.dk/en-GB/Applying/Study",
        "living_costs": [("کپنهاگ", "DKK 9,500 تا 14,000", "هزینه بالا"), ("سایر شهرها", "DKK 7,500 تا 11,000", "مقرون به صرفه تر")],
        "tuition": [("Non-EU", "EUR 8,000 تا 16,000 سالانه")],
        "scholarships": [("Danish Government Scholarships", "معافیت شهریه + کمک هزینه محدود"), ("University Grants", "بر پایه رزومه")],
        "pros": ["آموزش عملی و پروژه محور", "کیفیت زندگی بالا", "جامعه نوآور"],
        "cons": ["هزینه زندگی بالا", "بازار کار رقابتی برای غیر دانمارکی زبان"],
        "image_queries": ["Denmark university design school", "Denmark student residence permit", "Copenhagen student biking"],
    },
    "finland": {
        "hook": "به دلیل آموزش مدرن، نوآوری و کیفیت بالای دانشگاه های کاربردی شناخته می شود.",
        "intl_students": "حدود ۳۰ هزار",
        "cities": [("هلسینکی", "فرصت های فناوری و استارتاپ"), ("تامپره", "دانشگاهی و صنعتی")],
        "popular_fields": ["Game Development", "AI", "مهندسی", "آموزش", "Business"],
        "language_note": "برنامه های انگلیسی در ارشد قوی است؛ فنلاندی برای ادغام شغلی بلندمدت کمک می کند.",
        "official_visa_url": "https://migri.fi/en/studying-in-finland",
        "living_costs": [("هلسینکی", "EUR 900 تا 1,400", "اجاره بخش مهم هزینه"), ("سایر شهرها", "EUR 700 تا 1,100", "متعادل تر")],
        "tuition": [("Non-EU", "EUR 6,000 تا 18,000 سالانه")],
        "scholarships": [("Finland Scholarship", "معافیت شهریه + کمک هزینه سال اول در برخی دانشگاه ها"), ("University Waiver", "تخفیف جزئی یا کامل شهریه")],
        "pros": ["کیفیت آموزش و رفاه بالا", "سیستم دانشگاهی کاربردی", "محیط امن"],
        "cons": ["زمستان طولانی", "بازار کار نیازمند زبان محلی"],
        "image_queries": ["Finland university winter campus", "Finland student residence permit", "Helsinki student housing"],
    },
    "norway": {
        "hook": "با کیفیت زندگی ممتاز و دانشگاه های پژوهشی قوی، گزینه ای ارزشمند برای تحصیل است.",
        "intl_students": "حدود ۳۰ هزار",
        "cities": [("اسلو", "فرصت کاری و دانشگاهی بیشتر"), ("تروندهایم", "مرکز مهندسی و تکنولوژی")],
        "popular_fields": ["انرژی", "مهندسی دریایی", "علوم محیطی", "Data", "Business"],
        "language_note": "بعضی برنامه های ارشد انگلیسی هستند؛ برای کار پاره وقت نروژی مزیت ایجاد می کند.",
        "official_visa_url": "https://udi.no/en/want-to-apply/studies/studietillatelse/",
        "living_costs": [("اسلو", "NOK 13,000 تا 20,000", "هزینه بالا"), ("شهرهای دیگر", "NOK 10,000 تا 15,000", "متعادل تر")],
        "tuition": [("دولتی", "در بسیاری برنامه ها شهریه پایین تر/جدیدا در برخی دانشگاه ها شهریه اضافه شده"), ("خصوصی", "متغیر")],
        "scholarships": [("University Funding", "گرنت های محدود داخلی"), ("Nordic/Erasmus options", "برنامه های تبادلی")],
        "pros": ["امنیت و کیفیت زندگی بسیار بالا", "طبیعت و محیط پاک", "پژوهش قوی"],
        "cons": ["هزینه زندگی بالا", "ظرفیت محدود برنامه های انگلیسی"],
        "image_queries": ["Norway technical university campus", "Norway study permit office", "Oslo student neighborhood"],
    },
    "portugal": {
        "hook": "هزینه زندگی مناسب تر در اروپای غربی و محیط دانشجویی دوستانه دارد.",
        "intl_students": "حدود ۷۰ هزار",
        "cities": [("لیسبون", "مرکز اصلی دانشگاه ها"), ("پورتو", "دانشگاهی و هزینه کمتر")],
        "popular_fields": ["Business", "گردشگری", "مهندسی", "علوم داده", "هنر"],
        "language_note": "برنامه های انگلیسی به ویژه در ارشد بیشتر شده؛ پرتغالی برای کار پاره وقت مفید است.",
        "official_visa_url": "https://vistos.mne.gov.pt/en/national-visas/general-information/type-of-visa",
        "living_costs": [("لیسبون", "EUR 850 تا 1,300", "اجاره نسبتا بالا"), ("پورتو/کویمبرا", "EUR 650 تا 1,000", "اقتصادی تر")],
        "tuition": [("دولتی", "EUR 3,000 تا 7,500"), ("خصوصی", "EUR 5,000 تا 12,000")],
        "scholarships": [("DGES/University Grants", "حمایت دانشگاهی محدود"), ("Erasmus+", "برای بخشی از دوره یا تبادل")],
        "pros": ["هزینه مناسب", "آب وهوا و سبک زندگی خوب", "مسیر اقامت قابل پیگیری"],
        "cons": ["نیاز به زبان پرتغالی برای بسیاری مشاغل", "ظرفیت محدود فاند کامل"],
        "image_queries": ["Portugal university campus", "Portugal student visa office", "Lisbon student tram"],
    },
    "poland": {
        "hook": "با هزینه تحصیل و زندگی مناسب، گزینه اقتصادی محبوب در اروپای مرکزی است.",
        "intl_students": "حدود ۱۰۰ هزار",
        "cities": [("ورشو", "فرصت کاری بیشتر"), ("کراکوف", "شهر دانشجویی تاریخی")],
        "popular_fields": ["پزشکی", "مهندسی", "IT", "Business", "داروسازی"],
        "language_note": "برنامه های انگلیسی زیادی وجود دارد؛ لهستانی برای کار دانشجویی مزیت است.",
        "official_visa_url": "https://www.gov.pl/web/diplomacy/visas",
        "living_costs": [("ورشو", "PLN 3,000 تا 4,800", "شامل اجاره"), ("سایر شهرها", "PLN 2,200 تا 3,700", "مقرون به صرفه تر")],
        "tuition": [("برنامه انگلیسی", "EUR 2,500 تا 8,000"), ("پزشکی", "EUR 10,000 تا 16,000")],
        "scholarships": [("NAWA", "بورسیه های رقابتی دولتی"), ("University discounts", "تخفیف شهریه برای معدل بالا")],
        "pros": ["هزینه مناسب", "تنوع رشته انگلیسی", "موقعیت خوب در اروپا"],
        "cons": ["زمستان سرد", "کیفیت دانشگاه ها ناهمگون"],
        "image_queries": ["Poland university campus Krakow", "Poland student visa stamp", "Warsaw student housing"],
    },
    "czech": {
        "hook": "کشوری با کیفیت آموزشی خوب، هزینه متوسط و موقعیت عالی در اروپای مرکزی است.",
        "intl_students": "حدود ۵۰ هزار",
        "cities": [("پراگ", "محبوب ترین شهر دانشجویی"), ("برنو", "قطب مهندسی و IT")],
        "popular_fields": ["پزشکی", "مهندسی", "IT", "اقتصاد", "علوم پایه"],
        "language_note": "برنامه های انگلیسی وجود دارد؛ یادگیری چکی برای کار روزمره کمک کننده است.",
        "official_visa_url": "https://frs.gov.cz/en/visa-and-residence-permit-types/third-country-nationals/long-term-visa/",
        "living_costs": [("پراگ", "CZK 20,000 تا 32,000", "اجاره مهم ترین بخش"), ("برنو", "CZK 16,000 تا 26,000", "متعادل تر")],
        "tuition": [("برنامه انگلیسی", "EUR 3,000 تا 12,000"), ("برنامه چکی در دولتی", "اغلب رایگان یا بسیار پایین")],
        "scholarships": [("Government Scholarships", "برنامه های محدود دولتی"), ("University merit support", "کمک هزینه داخلی")],
        "pros": ["هزینه مناسب", "کیفیت خوب برخی دانشگاه ها", "دسترسی آسان به اروپا"],
        "cons": ["نیاز به زبان محلی برای برخی کارها", "بروکراسی اقامت"],
        "image_queries": ["Czech Republic university campus", "Czech student visa office", "Prague student tram"],
    },
    "hungary": {
        "hook": "به دلیل شهریه مناسب و بورسیه دولتی Stipendium Hungaricum بین ایرانی ها شناخته شده است.",
        "intl_students": "حدود ۴۰ هزار",
        "cities": [("بوداپست", "مرکز اصلی دانشگاه ها"), ("دبرسن", "دانشگاهی و آرام تر")],
        "popular_fields": ["پزشکی", "دندانپزشکی", "داروسازی", "مهندسی", "Business"],
        "language_note": "رشته های انگلیسی فراوان است؛ برای کار خارج دانشگاه، مجاری مفید خواهد بود.",
        "official_visa_url": "https://enterhungary.gov.hu/eh/",
        "living_costs": [("بوداپست", "EUR 700 تا 1,200", "اجاره رو به افزایش"), ("سایر شهرها", "EUR 550 تا 900", "مناسب تر")],
        "tuition": [("پزشکی", "EUR 12,000 تا 18,000"), ("سایر رشته ها", "EUR 3,000 تا 10,000")],
        "scholarships": [("Stipendium Hungaricum", "بورسیه دولتی با شهریه و کمک هزینه"), ("University Scholarships", "تخفیف محدود")],
        "pros": ["بورسیه معروف دولتی", "هزینه نسبتا مناسب", "موقعیت مرکزی در اروپا"],
        "cons": ["رقابت بالا برای رشته های پزشکی", "بازار کار محلی نیازمند زبان"],
        "image_queries": ["Hungary university campus Budapest", "Hungary student residence permit", "Budapest student district"],
    },
    "greece": {
        "hook": "گزینه ای اقتصادی در جنوب اروپا با محیط فرهنگی غنی و آب وهوای مطلوب است.",
        "intl_students": "حدود ۳۵ هزار",
        "cities": [("آتن", "مرکز دانشگاهی و اداری"), ("تسالونیکی", "شهر دانشجویی محبوب")],
        "popular_fields": ["باستان شناسی", "Business", "دریانوردی", "گردشگری", "مهندسی"],
        "language_note": "برنامه های انگلیسی در حال گسترش است؛ یونانی برای کار روزمره مزیت مهمی است.",
        "official_visa_url": "https://migration.gov.gr/en/nomothesia/adeies-diamonis/",
        "living_costs": [("آتن", "EUR 700 تا 1,150", "اجاره بخش اصلی"), ("تسالونیکی", "EUR 600 تا 950", "متعادل تر")],
        "tuition": [("دولتی (برخی برنامه ها)", "EUR 1,500 تا 4,000"), ("خصوصی/بین المللی", "EUR 5,000 تا 12,000")],
        "scholarships": [("IKY Scholarships", "برنامه های محدود بورسیه"), ("University grants", "کمک هزینه دانشگاهی")],
        "pros": ["هزینه قابل مدیریت", "فرهنگ و آب وهوا مناسب", "دسترسی به اتحادیه اروپا"],
        "cons": ["فرصت فاند محدود", "بازار کار محلی رقابتی"],
        "image_queries": ["Greece university campus Athens", "Greece student visa process", "Thessaloniki student street"],
    },
    "turkey": {
        "hook": "به دلیل نزدیکی فرهنگی و هزینه مناسب، برای دانشجویان ایرانی گزینه عملی محسوب می شود.",
        "intl_students": "بیش از ۳۰۰ هزار",
        "cities": [("استانبول", "تنوع دانشگاه و فرصت شغلی"), ("آنکارا", "آکادمیک تر و اداری")],
        "popular_fields": ["پزشکی", "دندانپزشکی", "مهندسی", "Business", "معماری"],
        "language_note": "برنامه های ترکی و انگلیسی وجود دارد؛ برای زندگی روزانه دانستن ترکی مهم است.",
        "official_visa_url": "https://www.goc.gov.tr/ikamet-izinleri",
        "living_costs": [("استانبول", "USD 500 تا 900", "وابسته به نرخ ارز و اجاره"), ("آنکارا/ازمیر", "USD 400 تا 750", "اقتصادی تر")],
        "tuition": [("دولتی", "USD 500 تا 4,000"), ("خصوصی", "USD 4,000 تا 20,000+")],
        "scholarships": [("Turkiye Burslari", "بورسیه دولتی کامل و رقابتی"), ("University Discounts", "تخفیف شهریه")],
        "pros": ["نزدیکی جغرافیایی", "هزینه نسبتاً مناسب", "تنوع دانشگاهی"],
        "cons": ["نوسان اقتصادی", "کیفیت دانشگاه ها متفاوت"],
        "image_queries": ["Turkey university campus Istanbul", "Turkey student residence permit office", "Ankara student metro"],
    },
    "malaysia": {
        "hook": "هزینه مناسب، برنامه های انگلیسی و حضور شعب دانشگاه های بین المللی را همزمان دارد.",
        "intl_students": "حدود ۱۳۰ هزار",
        "cities": [("کوالالامپور", "مرکز اصلی دانشگاه ها"), ("جوهور", "هزینه زندگی کمی پایین تر")],
        "popular_fields": ["IT", "Business", "مهندسی", "Hospitality", "رشته های سلامت"],
        "language_note": "بخش زیادی از آموزش به انگلیسی است و برای ایرانی ها تطبیق نسبتا آسان است.",
        "official_visa_url": "https://educationmalaysia.gov.my/visa/",
        "living_costs": [("کوالالامپور", "MYR 2,000 تا 3,800", "هزینه متوسط"), ("شهرهای دیگر", "MYR 1,600 تا 3,000", "مقرون به صرفه تر")],
        "tuition": [("دانشگاه دولتی", "MYR 8,000 تا 20,000"), ("خصوصی/بین المللی", "MYR 20,000 تا 50,000")],
        "scholarships": [("MIS Scholarship", "حمایت محدود دولتی"), ("University merit awards", "تخفیف شهریه")],
        "pros": ["هزینه مناسب", "زبان انگلیسی در آموزش", "تنوع فرهنگی"],
        "cons": ["گرما و رطوبت بالا", "رتبه دانشگاهی نامتوازن"],
        "image_queries": ["Malaysia university campus", "Malaysia student pass office", "Kuala Lumpur student apartment"],
    },
    "uae": {
        "hook": "با زیرساخت مدرن و حضور دانشگاه های بین المللی، مسیر سریع تری برای شروع تحصیل می دهد.",
        "intl_students": "حدود ۸۰ هزار",
        "cities": [("دبی", "دانشگاه های بین المللی و فرصت کار"), ("ابوظبی", "کیفیت زندگی بالا و دانشگاه های قوی")],
        "popular_fields": ["Business", "Aviation", "IT", "Hospitality", "Media"],
        "language_note": "اکثر برنامه ها انگلیسی هستند و محیط چندفرهنگی است.",
        "official_visa_url": "https://icp.gov.ae/en/service/issuing-a-residence-visa-for-students/",
        "living_costs": [("دبی", "AED 3,500 تا 6,500", "اجاره بخش اصلی"), ("ابوظبی/شارجه", "AED 2,800 تا 5,200", "گزینه متعادل تر")],
        "tuition": [("دانشگاه های بین المللی", "AED 35,000 تا 90,000 سالانه")],
        "scholarships": [("Institutional Scholarships", "بورسیه داخلی دانشگاه ها"), ("Merit Discounts", "تخفیف بر اساس معدل")],
        "pros": ["فرآیند سریع و عملی", "زبان انگلیسی", "نزدیکی جغرافیایی به ایران"],
        "cons": ["هزینه شهریه بالا در برخی دانشگاه ها", "وابستگی زیاد به توان مالی"],
        "image_queries": ["UAE university campus Dubai", "UAE student residence visa office", "Dubai metro students"],
    },
    "saudi_arabia": {
        "hook": "با سرمایه گذاری گسترده آموزشی و بورسیه های دولتی در حال تبدیل شدن به مقصد منطقه ای است.",
        "intl_students": "رو به رشد",
        "cities": [("ریاض", "دانشگاه های بزرگ و تحقیقاتی"), ("جده", "بین المللی تر و ساحلی")],
        "popular_fields": ["مهندسی", "علوم کامپیوتر", "Business", "علوم پزشکی", "انرژی"],
        "language_note": "برخی برنامه ها انگلیسی هستند؛ آشنایی با عربی برای تعامل روزمره مفید است.",
        "official_visa_url": "https://studyinsaudi.moe.gov.sa/",
        "living_costs": [("ریاض/جده", "SAR 2,500 تا 4,800", "وابسته به سبک زندگی"), ("شهرهای کوچک", "SAR 1,800 تا 3,200", "کم هزینه تر")],
        "tuition": [("دانشگاه های دولتی منتخب", "در برخی موارد همراه بورسیه"), ("خصوصی", "SAR 25,000 تا 70,000")],
        "scholarships": [("Study in Saudi Scholarships", "بورسیه دولتی در رشته های منتخب"), ("University Grants", "کمک هزینه داخلی")],
        "pros": ["بورسیه های در حال توسعه", "بازار کار منطقه ای", "نزدیکی فرهنگی برای برخی دانشجویان"],
        "cons": ["تنوع برنامه انگلیسی محدودتر از غرب", "نیاز به شناخت دقیق مقررات دانشگاهی"],
        "image_queries": ["Saudi Arabia university campus", "Saudi student visa process", "Riyadh student housing"],
    },
    "qatar": {
        "hook": "با Campus های بین المللی در Education City گزینه فشرده و باکیفیتی ارائه می کند.",
        "intl_students": "حدود ۱۵ هزار",
        "cities": [("دوحه", "تمرکز اصلی آموزش عالی"), ("Education City", "حضور شعب دانشگاه های بین المللی")],
        "popular_fields": ["روابط بین الملل", "مهندسی", "Business", "علوم پزشکی", "رسانه"],
        "language_note": "برنامه های زیادی انگلیسی هستند و محیط دانشگاهی بین المللی است.",
        "official_visa_url": "https://portal.www.gov.qa/wps/portal/services/inviduallandingpages/residence%20permits/issuingresidencepermit",
        "living_costs": [("دوحه", "QAR 4,000 تا 7,000", "اجاره و حمل ونقل بالا"), ("خوابگاه", "QAR 2,500 تا 4,500", "مقرون به صرفه تر")],
        "tuition": [("University branches", "QAR 60,000 تا 220,000 سالانه (وابسته به دانشگاه)")],
        "scholarships": [("Qatar Foundation Scholarships", "بورسیه و حمایت شهریه"), ("University merit aid", "تخفیف شهریه")],
        "pros": ["دانشگاه های بین المللی", "امنیت بالا", "نزدیکی جغرافیایی"],
        "cons": ["هزینه شهریه بالا", "انتخاب رشته محدودتر"],
        "image_queries": ["Qatar Education City campus", "Qatar student residence permit", "Doha student life"],
    },
    "india": {
        "hook": "با طیف وسیع دانشگاه و هزینه قابل کنترل، گزینه ای منعطف برای بودجه های مختلف است.",
        "intl_students": "بیش از ۵۰ هزار",
        "cities": [("بنگلور", "فناوری و استارتاپ"), ("پونه", "شهر دانشجویی با هزینه متعادل")],
        "popular_fields": ["IT", "مهندسی", "Business", "داروسازی", "پزشکی"],
        "language_note": "انگلیسی در آموزش عالی بسیار رایج است و ورود اولیه را آسان می کند.",
        "official_visa_url": "https://indianvisaonline.gov.in/",
        "living_costs": [("شهرهای بزرگ", "INR 20,000 تا 45,000", "وابسته به نوع اقامت"), ("شهرهای دانشجویی", "INR 15,000 تا 30,000", "اقتصادی تر")],
        "tuition": [("دانشگاه دولتی", "INR 60,000 تا 300,000 سالانه"), ("خصوصی", "INR 200,000 تا 1,500,000+")],
        "scholarships": [("ICCR", "بورسیه دولتی برای دانشجویان خارجی"), ("Institutional aid", "تخفیف شهریه در برخی دانشگاه ها")],
        "pros": ["تنوع زیاد دانشگاه", "هزینه زندگی قابل مدیریت", "آموزش انگلیسی رایج"],
        "cons": ["کیفیت دانشگاه ها بسیار متفاوت", "تراکم شهری در برخی شهرها"],
        "image_queries": ["India university campus Bangalore", "India student visa office", "Pune student hostel"],
    },
    "thailand": {
        "hook": "دانشگاه های بین المللی با هزینه مناسب تر نسبت به بسیاری از مقاصد آسیایی دارد.",
        "intl_students": "حدود ۳۰ هزار",
        "cities": [("بانکوک", "مرکز اصلی دانشگاهی"), ("چیانگ مای", "آرام تر و اقتصادی تر")],
        "popular_fields": ["Hospitality", "Business", "IT", "Public Health", "علوم دریایی"],
        "language_note": "برنامه های انگلیسی در دانشگاه های بین المللی ارائه می شود؛ تایلندی برای زندگی روزمره کمک می کند.",
        "official_visa_url": "https://www.immigration.go.th/en/",
        "living_costs": [("بانکوک", "THB 22,000 تا 40,000", "متوسط"), ("چیانگ مای", "THB 16,000 تا 30,000", "مناسب تر")],
        "tuition": [("برنامه انگلیسی", "THB 120,000 تا 350,000 سالانه")],
        "scholarships": [("Thailand Scholarships", "طرح های محدود دولتی"), ("University merit scholarships", "تخفیف شهریه")],
        "pros": ["هزینه مناسب", "محیط بین المللی در دانشگاه های اصلی", "سبک زندگی راحت"],
        "cons": ["تنوع محدود دانشگاه های رتبه بالا", "نیاز به تایلندی برای کار محلی"],
        "image_queries": ["Thailand university campus Bangkok", "Thailand student visa office", "Chiang Mai student district"],
    },
    "israel": {
        "hook": "در حوزه های فناوری و پژوهش نوآورانه، یکی از قوی ترین اکوسیستم های منطقه را دارد.",
        "intl_students": "حدود ۱۵ هزار",
        "cities": [("تل آویو", "استارتاپ و فناوری"), ("اورشلیم", "پژوهش و علوم انسانی")],
        "popular_fields": ["علوم کامپیوتر", "AI", "مهندسی برق", "علوم زیستی", "Business"],
        "language_note": "برخی برنامه های بین المللی انگلیسی هستند؛ عبری برای کار روزمره مزیت دارد.",
        "official_visa_url": "https://www.gov.il/en/service/apply_for_a_student_visa",
        "living_costs": [("تل آویو", "USD 1,300 تا 2,300", "اجاره بالا"), ("حیفا/اورشلیم", "USD 1,000 تا 1,800", "کمی متعادل تر")],
        "tuition": [("دانشگاه ها", "USD 10,000 تا 20,000")],
        "scholarships": [("Israel Government Scholarships", "بورسیه های محدود"), ("University Research Grants", "حمایت پژوهشی")],
        "pros": ["اکوسیستم نوآوری قوی", "کیفیت پژوهش بالا", "ارتباط نزدیک صنعت و دانشگاه"],
        "cons": ["هزینه زندگی بالا", "حساسیت های سیاسی و امنیتی"],
        "image_queries": ["Israel university research campus", "Israel student visa office", "Tel Aviv student neighborhood"],
    },
    "brazil": {
        "hook": "با دانشگاه های بزرگ و هزینه نسبتاً مناسب در آمریکای لاتین، مقصدی قابل بررسی است.",
        "intl_students": "حدود ۷۰ هزار",
        "cities": [("سائوپائولو", "بزرگ ترین قطب آموزشی و صنعتی"), ("کامپیناس", "دانشگاهی و پژوهشی")],
        "popular_fields": ["مهندسی", "کشاورزی", "Business", "علوم زیستی", "طراحی"],
        "language_note": "بیشتر برنامه ها پرتغالی هستند؛ برای برنامه های انگلیسی باید دانشگاه ها را دقیق انتخاب کرد.",
        "official_visa_url": "https://www.gov.br/mre/pt-br/consulado-londres/visas/vitem-iv-student-visa",
        "living_costs": [("سائوپائولو/ریو", "BRL 3,000 تا 5,500", "هزینه شهری بالاتر"), ("شهرهای دانشگاهی", "BRL 2,200 تا 4,000", "متعادل تر")],
        "tuition": [("دولتی", "برای خارجی ها بسته به برنامه ممکن است کم یا رایگان"), ("خصوصی", "BRL 15,000 تا 60,000 سالانه")],
        "scholarships": [("CAPES/CNPq", "حمایت پژوهشی عمدتا در تحصیلات تکمیلی"), ("University aid", "کمک هزینه محدود")],
        "pros": ["بازار بزرگ و پویا", "هزینه معقول نسبت به برخی مقاصد", "تنوع فرهنگی"],
        "cons": ["نیاز جدی به پرتغالی", "فاصله جغرافیایی زیاد از ایران"],
        "image_queries": ["Brazil university campus Sao Paulo", "Brazil student visa process", "Campinas student housing"],
    },
    "mexico": {
        "hook": "دانشگاه های معتبر منطقه ای با هزینه مناسب و فرهنگ دانشجویی فعال دارد.",
        "intl_students": "حدود ۴۰ هزار",
        "cities": [("مکزیکوسیتی", "تنوع دانشگاهی بالا"), ("مونتری", "قطب صنعتی و فناوری")],
        "popular_fields": ["Business", "مهندسی", "معماری", "علوم اجتماعی", "طراحی"],
        "language_note": "بخش زیادی از دوره ها اسپانیایی است؛ برنامه انگلیسی محدودتر ولی موجود است.",
        "official_visa_url": "https://www.gob.mx/tramites/ficha/visa-de-residente-temporal-estudiante/SRE260",
        "living_costs": [("مکزیکوسیتی", "USD 700 تا 1,300", "اجاره متغیر"), ("شهرهای دیگر", "USD 500 تا 950", "اقتصادی تر")],
        "tuition": [("دولتی", "USD 1,000 تا 4,000"), ("خصوصی", "USD 6,000 تا 20,000+")],
        "scholarships": [("AMEXCID", "بورسیه های محدود دولتی"), ("University grants", "کمک هزینه شهریه")],
        "pros": ["هزینه قابل مدیریت", "فرهنگ دانشجویی پرانرژی", "گزینه های متنوع شهری"],
        "cons": ["نیاز به اسپانیایی برای زندگی و کار", "کیفیت دانشگاه ها ناهمگون"],
        "image_queries": ["Mexico university campus", "Mexico student temporary resident visa", "Monterrey student district"],
    },
    "argentina": {
        "hook": "به خاطر دانشگاه های دولتی و هزینه تحصیل پایین، برای بودجه های محدود جذاب است.",
        "intl_students": "حدود ۱۰۰ هزار",
        "cities": [("بوئنوس آیرس", "بزرگ ترین مرکز دانشگاهی"), ("کوردوبا", "شهر دانشگاهی قدیمی")],
        "popular_fields": ["پزشکی", "علوم اجتماعی", "Business", "مهندسی", "هنر"],
        "language_note": "زبان اصلی اسپانیایی است و بدون آن فرصت کار/تعامل محدود می شود.",
        "official_visa_url": "https://www.argentina.gob.ar/interior/migraciones/residencias",
        "living_costs": [("بوئنوس آیرس", "USD 450 تا 900", "وابسته به تورم و نرخ ارز"), ("کوردوبا", "USD 350 تا 700", "اقتصادی تر")],
        "tuition": [("دانشگاه دولتی", "اغلب بسیار پایین یا رایگان"), ("خصوصی", "USD 3,000 تا 12,000")],
        "scholarships": [("University aid", "کمک هزینه محدود"), ("Bilateral programs", "طرح های تبادلی بین المللی")],
        "pros": ["تحصیل مقرون به صرفه", "جامعه دانشجویی بزرگ", "دانشگاه های معتبر منطقه ای"],
        "cons": ["نوسان اقتصادی", "وابستگی بالا به اسپانیایی"],
        "image_queries": ["Argentina university campus Buenos Aires", "Argentina student residence process", "Cordoba student street"],
    },
    "chile": {
        "hook": "کشوری با ثبات نسبی در آمریکای لاتین و دانشگاه های پژوهش محور است.",
        "intl_students": "حدود ۳۰ هزار",
        "cities": [("سانتیاگو", "مرکز اصلی دانشگاه ها"), ("والپارایسو", "فرهنگی و دانشجویی")],
        "popular_fields": ["مهندسی معدن", "Business", "علوم محیطی", "IT", "روابط بین الملل"],
        "language_note": "برنامه های انگلیسی محدودتر است و اسپانیایی در عمل ضروری می شود.",
        "official_visa_url": "https://serviciomigraciones.cl/en/residencia-temporal/subcategorias/estudiantes/",
        "living_costs": [("سانتیاگو", "USD 600 تا 1,100", "اجاره متوسط"), ("شهرهای دیگر", "USD 450 تا 850", "کم هزینه تر")],
        "tuition": [("دانشگاه ها", "USD 3,000 تا 10,000 سالانه")],
        "scholarships": [("ANID options", "حمایت پژوهشی محدود"), ("University aid", "تخفیف شهریه")],
        "pros": ["ثبات نسبی منطقه ای", "کیفیت خوب برخی دانشگاه ها", "بازار کار تخصصی در بخش معدن/انرژی"],
        "cons": ["نیاز به اسپانیایی", "گزینه بورسیه محدود"],
        "image_queries": ["Chile university campus Santiago", "Chile student temporary residence permit", "Valparaiso student life"],
    },
    "south_africa": {
        "hook": "دانشگاه های معتبر آفریقا با شهریه نسبتا مناسب و محیط آکادمیک انگلیسی دارد.",
        "intl_students": "حدود ۴۰ هزار",
        "cities": [("کیپ تاون", "دانشگاه های مطرح و کیفیت زندگی خوب"), ("ژوهانسبورگ", "فرصت های اقتصادی بیشتر")],
        "popular_fields": ["Public Health", "Mining Engineering", "Business", "IT", "علوم اجتماعی"],
        "language_note": "زبان آموزشی اغلب انگلیسی است و برای دانشجوی ایرانی مزیت مهمی محسوب می شود.",
        "official_visa_url": "https://www.dha.gov.za/index.php/immigration-services/types-of-temporary-permits",
        "living_costs": [("کیپ تاون", "ZAR 9,000 تا 16,000", "اجاره و حمل ونقل"), ("ژوهانسبورگ", "ZAR 8,000 تا 14,000", "کمی اقتصادی تر")],
        "tuition": [("دانشگاه ها", "ZAR 45,000 تا 120,000 سالانه")],
        "scholarships": [("University bursaries", "حمایت محدود داخلی"), ("Research scholarships", "برای تحصیلات تکمیلی")],
        "pros": ["زبان انگلیسی", "دانشگاه های معتبر قاره", "هزینه مناسب تر نسبت به غرب"],
        "cons": ["ملاحظات امنیتی در برخی مناطق", "فاصله جغرافیایی بالا"],
        "image_queries": ["South Africa university campus Cape Town", "South Africa study visa permit", "Johannesburg student housing"],
    },
    "egypt": {
        "hook": "برای رشته های پزشکی و منطقه ای با هزینه قابل کنترل، گزینه ای در حال رشد است.",
        "intl_students": "حدود ۹۰ هزار",
        "cities": [("قاهره", "بیشترین تمرکز دانشگاهی"), ("اسکندریه", "دانشگاهی و ساحلی")],
        "popular_fields": ["پزشکی", "دندانپزشکی", "مهندسی", "Business", "مطالعات عربی"],
        "language_note": "برخی رشته ها انگلیسی هستند؛ عربی برای امور اداری و کار روزمره مفید است.",
        "official_visa_url": "https://visa2egypt.gov.eg/",
        "living_costs": [("قاهره", "USD 300 تا 650", "اقتصادی نسبت به بسیاری کشورها"), ("شهرهای دیگر", "USD 220 تا 500", "پایین تر")],
        "tuition": [("دانشگاه ها", "USD 2,500 تا 8,000"), ("پزشکی", "ممکن است بالاتر باشد")],
        "scholarships": [("University-based discounts", "تخفیف شهریه برای بین المللی"), ("Bilateral options", "برنامه های تبادلی محدود")],
        "pros": ["هزینه پایین", "نزدیکی جغرافیایی", "تنوع رشته های پزشکی"],
        "cons": ["پیچیدگی اداری در برخی مراحل", "تنوع کیفیت دانشگاه ها"],
        "image_queries": ["Egypt university campus Cairo", "Egypt visa office documents", "Alexandria student district"],
    },
    "russia": {
        "hook": "با دانشگاه های بزرگ و سهمیه های بورسیه دولتی، مقصدی پرتقاضا برای برخی رشته هاست.",
        "intl_students": "بیش از ۳۵۰ هزار",
        "cities": [("مسکو", "دانشگاه های سطح بالا"), ("سن پترزبورگ", "محیط دانشگاهی و فرهنگی قوی")],
        "popular_fields": ["پزشکی", "مهندسی", "هوافضا", "ریاضی", "علوم پایه"],
        "language_note": "بسیاری از برنامه ها روسی هستند؛ دوره پادفک برای آماده سازی زبان رایج است.",
        "official_visa_url": "https://studyinrussia.ru/en/life-in-russia/visa-for-foreign-students/",
        "living_costs": [("مسکو", "RUB 55,000 تا 95,000", "وابسته به خوابگاه/اجاره"), ("سایر شهرها", "RUB 35,000 تا 65,000", "پایین تر")],
        "tuition": [("دانشگاه ها", "RUB 180,000 تا 450,000 سالانه"), ("پزشکی", "بالاتر از میانگین")],
        "scholarships": [("Russian Government Quota", "بورسیه سهمیه ای دولتی"), ("University grants", "کمک هزینه محدود")],
        "pros": ["بورسیه دولتی سهمیه ای", "رشته های فنی قوی", "هزینه قابل مدیریت در شهرهای غیرمرکزی"],
        "cons": ["نیاز جدی به زبان روسی", "زمستان سخت و طولانی"],
        "image_queries": ["Russia university campus Moscow", "Russia student visa process", "Saint Petersburg student metro"],
    },
    "taiwan": {
        "hook": "دانشگاه های تکنولوژی محور با کیفیت بالا و هزینه معقول در شرق آسیا ارائه می دهد.",
        "intl_students": "حدود ۱۲۰ هزار",
        "cities": [("تایپه", "قطب فناوری و دانشگاهی"), ("تایچونگ", "هزینه متعادل تر")],
        "popular_fields": ["مهندسی برق", "علوم کامپیوتر", "Business", "Semiconductor", "طراحی"],
        "language_note": "برخی برنامه ها انگلیسی هستند؛ ماندارین برای زندگی و کار پاره وقت بسیار مهم است.",
        "official_visa_url": "https://www.boca.gov.tw/cp-166-281-0ddc6-2.html",
        "living_costs": [("تایپه", "TWD 28,000 تا 45,000", "اجاره بالا"), ("شهرهای دیگر", "TWD 22,000 تا 35,000", "متعادل تر")],
        "tuition": [("دانشگاه ها", "TWD 90,000 تا 170,000 سالانه")],
        "scholarships": [("Taiwan Scholarship", "بورسیه دولتی برای بین المللی"), ("MOE Huayu/University aid", "حمایت زبان یا شهریه")],
        "pros": ["صنعت تکنولوژی قوی", "کیفیت آموزش خوب", "هزینه مناسب تر از برخی مقاصد شرق آسیا"],
        "cons": ["لزوم ماندارین برای بازار کار", "رقابت بالا در دانشگاه های برتر"],
        "image_queries": ["Taiwan university campus Taipei", "Taiwan student visa BOCA", "Taipei student MRT"],
    },
}


def _finalize_fact(code: str, raw: dict[str, Any]) -> dict[str, Any]:
    name = raw.get("name") or WORLD_STUDY_COUNTRY_LABELS[code]
    hook = raw.get("hook", "یکی از مقاصد رو به رشد تحصیلی برای دانشجویان ایرانی محسوب می شود.")

    visa_sections = raw.get("visa_sections") or _default_visa_sections(name)
    image_queries = raw.get("image_queries") or _default_image_queries(code)

    fact: dict[str, Any] = {
        "code": code,
        "name": name,
        "hook": hook,
        "intl_students": raw.get("intl_students", ""),
        "degrees": raw.get("degrees", DEFAULT_DEGREES),
        "cities": raw.get("cities", []),
        "popular_fields": raw.get("popular_fields", []),
        "language_note": raw.get("language_note", ""),
        "description_extra": raw.get(
            "description_extra",
            "<p>اگر هدفتان پذیرش مطمئن است، حتما قبل از اپلای نهایی، هزینه واقعی شهر مقصد و شانس بورسیه را دقیق بررسی کنید.</p>",
        ),
        "visa_name": raw.get("visa_name", "ویزای تحصیلی"),
        "visa_sections": visa_sections,
        "visa_finance": raw.get("visa_finance", "تمکن مالی باید شهریه و هزینه زندگی سال اول را پوشش دهد."),
        "work_rights": raw.get("work_rights", "حق کار دانشجویی بسته به قانون کشور و نوع برنامه تعیین می شود."),
        "post_study": raw.get("post_study", "در بسیاری کشورها مسیر اقامت کاری پس از فارغ التحصیلی وجود دارد."),
        "official_visa_url": raw.get("official_visa_url", ""),
        "visa_extra": raw.get(
            "visa_extra",
            "<p><strong>نکته عملی:</strong> ترجمه رسمی مدارک مالی و برنامه پرداخت شهریه را از ابتدا منسجم آماده کنید تا ریسک ریجکتی پایین بیاید.</p>",
        ),
        "admission_steps": raw.get("admission_steps", DEFAULT_ADMISSION_STEPS),
        "lang_requirements": raw.get("lang_requirements", DEFAULT_LANG_REQUIREMENTS),
        "deadlines": raw.get(
            "deadlines",
            "برای ورودی اصلی، معمولا ۶ تا ۱۰ ماه قبل از شروع ترم اقدام کنید تا زمان کافی برای ویزا و اسکان داشته باشید.",
        ),
        "documents": raw.get("documents", DEFAULT_DOCS),
        "admission_extra": raw.get(
            "admission_extra",
            "<p>اگر بین چند دانشگاه مردد هستید، رتبه، هزینه کل، نرخ اشتغال فارغ التحصیلان و شانس ویزا را کنار هم مقایسه کنید.</p>",
        ),
        "living_costs": raw.get("living_costs", []),
        "tuition": raw.get("tuition", []),
        "housing_note": raw.get("housing_note", "برای ترم اول، خوابگاه دانشگاهی یا اقامت کوتاه مدت امن ترین انتخاب است."),
        "living_extra": raw.get(
            "living_extra",
            "<p>برای کنترل هزینه ها، خرید ماهانه، حمل ونقل دانشجویی و اقامت اشتراکی را از ابتدا در بودجه بندی لحاظ کنید.</p>",
        ),
        "scholarship_intro": raw.get(
            "scholarship_intro",
            f"در {name} ترکیبی از بورسیه های دانشگاهی و دولتی وجود دارد؛ زمان بندی و کیفیت SOP در نتیجه بسیار اثرگذار است.",
        ),
        "scholarships": raw.get("scholarships", []),
        "scholarship_tips": raw.get(
            "scholarship_tips",
            "برای بورسیه، روی معدل، مدرک زبان قوی، CV مستند و انگیزه نامه شخصی سازی شده تمرکز کنید.",
        ),
        "scholarship_extra": raw.get(
            "scholarship_extra",
            "<p>تجربه نشان داده ارسال پرونده کامل حداقل ۲ تا ۳ هفته قبل از ددلاین، شانس ارزیابی دقیق تر را بالا می برد.</p>",
        ),
        "pros": raw.get("pros", []),
        "cons": raw.get("cons", []),
        "pathway_duration": raw.get("pathway_duration", "۹ تا ۱۵ ماه"),
        "pathway_stats": raw.get(
            "pathway_stats",
            [("آماده سازی مدارک", "۴ تا ۸ هفته"), ("پذیرش", "۶ تا ۱۲ هفته"), ("ویزا", "۴ تا ۱۰ هفته"), ("اسکان", "۲ تا ۶ هفته")],
        ),
        "pathway_steps": raw.get("pathway_steps", _default_pathway_steps(name)),
        "headline": raw.get("headline", f"تحصیل در {name}؛ راهنمای پذیرش، ویزا و هزینه ۲۰۲۶"),
        "intro": raw.get(
            "intro",
            f"اگر قصد تحصیل در {name} را دارید، این راهنما به زبان ساده مسیر انتخاب رشته، اپلای، ویزا و زندگی دانشجویی را توضیح می دهد.",
        ),
        "search_keywords": raw.get("search_keywords", f"تحصیل در {name}, ویزای {name}, دانشگاه های {name}, اپلای {name}"),
        "meta_title": raw.get("meta_title", f"تحصیل در {name} ۲۰۲۶ | ویزا، پذیرش و بورسیه"),
        "meta_description": raw.get(
            "meta_description",
            f"راهنمای جامع تحصیل در {name}: شرایط پذیرش، ویزای دانشجویی، شهریه، هزینه زندگی و بورسیه برای دانشجویان ایرانی.",
        ),
        "image_queries": image_queries[:3],
    }
    return fact


WORLD_COUNTRY_FACTS: dict[str, dict] = {
    code: _finalize_fact(code, RAW_WORLD_FACTS[code])
    for code in WORLD_STUDY_COUNTRY_CODES
    if code in RAW_WORLD_FACTS
}


def get_world_country_facts(code: str) -> dict | None:
    return WORLD_COUNTRY_FACTS.get((code or "").strip().lower())


def all_world_country_facts() -> list[dict]:
    return [WORLD_COUNTRY_FACTS[code] for code in WORLD_STUDY_COUNTRY_CODES if code in WORLD_COUNTRY_FACTS]

