# Generated by Django 4.2.30 on 2026-07-22 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0073_add_institute_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone_normalized', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='موبایل نرمال')),
                ('phone_display', models.CharField(blank=True, max_length=30, verbose_name='موبایل نمایشی')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='کد پرونده')),
                ('stage', models.CharField(choices=[('attraction', 'جذب'), ('initial_consult', 'مشاوره اولیه'), ('follow_up', 'پیگیری'), ('specialized_consult', 'مشاوره تخصصی'), ('file_open', 'تشکیل پرونده'), ('admission', 'پذیرش'), ('visa', 'ویزا'), ('dispatch', 'اعزام'), ('won', 'موفق'), ('lost', 'مختومه')], db_index=True, default='attraction', max_length=32, verbose_name='مرحله')),
                ('status', models.CharField(choices=[('open', 'باز'), ('waiting', 'منتظر مشتری'), ('closed_won', 'موفق / بسته'), ('closed_lost', 'مختومه')], db_index=True, default='open', max_length=20, verbose_name='وضعیت')),
                ('progress', models.PositiveSmallIntegerField(default=10, verbose_name='پیشرفت ٪')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('normal', 'معمولی'), ('high', 'بالا'), ('urgent', 'فوری')], db_index=True, default='normal', max_length=10, verbose_name='اولویت')),
                ('source_type', models.CharField(choices=[('evaluation', 'ارزیابی'), ('consultation', 'رزرو مشاوره'), ('contact', 'تماس با ما'), ('manual', 'ورود دستی')], db_index=True, default='manual', max_length=20, verbose_name='منبع')),
                ('next_follow_up_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='پیگیری بعدی')),
                ('last_contact_result', models.CharField(blank=True, max_length=32, verbose_name='آخرین نتیجه تماس')),
                ('loss_reason', models.CharField(blank=True, choices=[('not_interested', 'عدم علاقه\u200cمندی'), ('budget', 'بودجه'), ('other_agency', 'مؤسسه دیگر'), ('no_answer', 'عدم پاسخ طولانی'), ('visa_reject', 'رد ویزا'), ('cancelled', 'انصراف'), ('other', 'سایر')], max_length=32, verbose_name='دلیل مختومه')),
                ('loss_note', models.CharField(blank=True, max_length=300, verbose_name='توضیح مختومه')),
                ('internal_notes', models.TextField(blank=True, verbose_name='یادداشت داخلی')),
                ('target_country', models.CharField(blank=True, max_length=50, verbose_name='کشور مقصد')),
                ('target_degree', models.CharField(blank=True, max_length=50, verbose_name='مقطع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بستن')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_assigned_cases', to=settings.AUTH_USER_MODEL, verbose_name='مسئول')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_cases', to='core.consultationrequest', verbose_name='مشاوره مرتبط')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='panel.customer', verbose_name='مشتری')),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_cases', to='core.evaluationrequest', verbose_name='ارزیابی مرتبط')),
            ],
            options={
                'verbose_name': 'پرونده پیگیری',
                'verbose_name_plural': 'پرونده\u200cهای پیگیری',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('note', 'یادداشت'), ('call', 'تماس'), ('stage_change', 'تغییر مرحله'), ('assign', 'تخصیص'), ('close', 'مختومه/بستن'), ('reopen', 'بازگشایی'), ('system', 'سیستم')], db_index=True, max_length=20, verbose_name='نوع')),
                ('contact_result', models.CharField(blank=True, choices=[('answered', 'پاسخ داد'), ('no_answer', 'عدم پاسخ'), ('busy', 'مشغول'), ('callback', 'تماس مجدد'), ('whatsapp', 'واتساپ'), ('not_interested', 'عدم علاقه'), ('converted', 'تبدیل / قرارداد')], max_length=32, verbose_name='نتیجه تماس')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True, verbose_name='پیگیری بعدی')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='panel.customercase', verbose_name='پرونده')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_case_events', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'رویداد پرونده',
                'verbose_name_plural': 'رویدادهای پرونده',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('kind', models.CharField(choices=[('initial', 'مشاوره اولیه'), ('specialized', 'مشاوره تخصصی'), ('other', 'سایر')], default='initial', max_length=20, verbose_name='نوع')),
                ('mode', models.CharField(choices=[('online', 'آنلاین'), ('in_person', 'حضوری')], default='online', max_length=20, verbose_name='حالت')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='شروع')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_appointments', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='panel.customercase', verbose_name='پرونده')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_appointments', to='core.consultationrequest')),
            ],
            options={
                'verbose_name': 'جلسه پرونده',
                'verbose_name_plural': 'جلسات پرونده',
                'ordering': ['starts_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customercase',
            index=models.Index(fields=['status', 'next_follow_up_at'], name='panel_case_st_fu_idx'),
        ),
        migrations.AddIndex(
            model_name='customercase',
            index=models.Index(fields=['assigned_to', 'status'], name='panel_case_asg_st_idx'),
        ),
        migrations.AddIndex(
            model_name='customercase',
            index=models.Index(fields=['stage', 'status'], name='panel_case_stage_st_idx'),
        ),
        migrations.AddIndex(
            model_name='caseevent',
            index=models.Index(fields=['case', 'created_at'], name='panel_evt_case_cr_idx'),
        ),
    ]
