# Generated by Django 4.2.30 on 2026-07-22 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import panel.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0073_add_institute_mobile'),
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercase',
            name='checklist',
            field=models.JSONField(blank=True, default=dict, help_text='کلید آیتم → True/False', verbose_name='چک\u200cلیست اعزام'),
        ),
        migrations.AddField(
            model_name='customercase',
            name='contact_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_cases', to='core.contactmessage', verbose_name='پیام تماس مرتبط'),
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='عنوان')),
                ('file', models.FileField(upload_to=panel.models.case_document_upload_to, verbose_name='فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='panel.customercase', verbose_name='پرونده')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_case_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مدرک پرونده',
                'verbose_name_plural': 'مدارک پرونده',
                'ordering': ['-created_at'],
            },
        ),
    ]
