# Generated by Django 4.2.30 on 2026-07-22 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0002_customercase_checklist_customercase_contact_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAssignmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='اگر خاموش باشد در نوبت خودکار/روزانه شرکت نمی\u200cکند.', verbose_name='فعال در تخصیص خودکار')),
                ('weight', models.PositiveSmallIntegerField(default=1, help_text='عدد بالاتر = سهم بیشتر در نوبتی.', verbose_name='وزن نوبت')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panel_assignment_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل تخصیص پرسنل',
                'verbose_name_plural': 'پروفایل\u200cهای تخصیص پرسنل',
                'ordering': ['sort_order', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='PanelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_assign_enabled', models.BooleanField(default=False, help_text='وقتی پرونده بدون مسئول ساخته شود، خودکار مسئول بگذار.', verbose_name='تخصیص خودکار پروندهٔ جدید')),
                ('auto_assign_mode', models.CharField(choices=[('round_robin', 'نوبتی (گردشی)'), ('least_load', 'کم\u200cبارترین مسئول'), ('fixed', 'همیشه یک نفر ثابت')], default='round_robin', max_length=20, verbose_name='روش تخصیص خودکار')),
                ('daily_followup_enabled', models.BooleanField(default=False, help_text='هر روز یک\u200cبار صف پیگیری/بدون\u200cمسئول را بین پرسنل فعال پخش کند.', verbose_name='توزیع روزانهٔ خودکار')),
                ('daily_followup_mode', models.CharField(choices=[('round_robin', 'نوبتی (گردشی)'), ('least_load', 'کم\u200cبارترین مسئول')], default='least_load', max_length=20, verbose_name='روش توزیع روزانه')),
                ('daily_followup_scope', models.CharField(choices=[('unassigned', 'فقط پرونده\u200cهای بدون مسئول'), ('followup_queue', 'بدون مسئول + موعد امروز/عقب\u200cافتاده')], default='followup_queue', max_length=20, verbose_name='دامنهٔ توزیع روزانه')),
                ('rr_cursor', models.PositiveIntegerField(default=0, verbose_name='نشانگر نوبتی')),
                ('last_daily_run_on', models.DateField(blank=True, null=True, verbose_name='آخرین اجرای روزانه')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixed_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_fixed_assignee_settings', to=settings.AUTH_USER_MODEL, verbose_name='مسئول ثابت')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تنظیمات پنل',
                'verbose_name_plural': 'تنظیمات پنل',
            },
        ),
    ]
